<?php
/**
 * AllowanceReasonType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AVACloud API 1.63.6
 *
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.63.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.49
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Dangl\AVACloud\Model;
use \Dangl\AVACloud\ObjectSerializer;

/**
 * AllowanceReasonType Class Doc Comment
 *
 * @category Class
 * @description Type specifying the identification of an allowance from UNTDID 5189. See this list: https://unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred5189.htm
 * @package  Dangl\AVACloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AllowanceReasonType
{
    /**
     * Possible values of this enum
     */
    const HANDLING_COMMISSION = 'HandlingCommission';
    const AMENDMENT_COMMISSION = 'AmendmentCommission';
    const ACCEPTANCE_COMMISSION = 'AcceptanceCommission';
    const COMMISSION_FOR_OBTAINING_ACCEPTANCE = 'CommissionForObtainingAcceptance';
    const COMMISSION_ON_DELIVERY = 'CommissionOnDelivery';
    const ADVISING_COMMISSION = 'AdvisingCommission';
    const CONFIRMATION_COMMISSION = 'ConfirmationCommission';
    const DEFERRED_PAYMENT_COMMISSION = 'DeferredPaymentCommission';
    const COMMISSION_FOR_TAKING_UP_DOCUMENTS = 'CommissionForTakingUpDocuments';
    const OPENING_COMMISSION = 'OpeningCommission';
    const FEE_FOR_PAYMENT_UNDER_RESERVE = 'FeeForPaymentUnderReserve';
    const DISCREPANCY_FEE = 'DiscrepancyFee';
    const DOMICILATION_COMMISSION = 'DomicilationCommission';
    const COMMISSION_FOR_RELEASE_OF_GOODS = 'CommissionForReleaseOfGoods';
    const COLLECTION_COMMISSION = 'CollectionCommission';
    const NEGOTIATION_COMMISSION = 'NegotiationCommission';
    const RETURN_COMMISSION = 'ReturnCommission';
    const BL_SPLITTING_CHARGES = 'BLSplittingCharges';
    const TRUST_COMMISSION = 'TrustCommission';
    const TRANSFER_COMMISSION = 'TransferCommission';
    const COMMISSION_FOR_OPENING_IRREVOCABLE_DOCUMENTARY_CREDITS = 'CommissionForOpeningIrrevocableDocumentaryCredits';
    const PRE_ADVICE_COMMISSION = 'PreAdviceCommission';
    const SUPERVISORY_COMMISSION = 'SupervisoryCommission';
    const MODEL_CHARGES = 'ModelCharges';
    const RISK_COMMISSION = 'RiskCommission';
    const GUARANTEE_COMMISSION = 'GuaranteeCommission';
    const REIMBURSEMENT_COMMISSION = 'ReimbursementCommission';
    const STAMP_DUTY = 'StampDuty';
    const BROKERAGE = 'Brokerage';
    const BANK_CHARGES = 'BankCharges';
    const BANK_CHARGES_INFORMATION = 'BankChargesInformation';
    const COURIER_FEE = 'CourierFee';
    const PHONE_FEE = 'PhoneFee';
    const POSTAGE_FEE = 'PostageFee';
    const SWIFT_FEE = 'SWIFTFee';
    const TELEX_FEE = 'TelexFee';
    const PENALTY_FOR_LATE_DELIVERY_OF_DOCUMENTS = 'PenaltyForLateDeliveryOfDocuments';
    const PENALTY_FOR_LATE_DELIVERY_OF_VALUATION_OF_WORKS = 'PenaltyForLateDeliveryOfValuationOfWorks';
    const PENALTY_FOR_EXECUTION_OF_WORKS_BEHIND_SCHEDULE = 'PenaltyForExecutionOfWorksBehindSchedule';
    const OTHER_PENALTIES = 'OtherPenalties';
    const BONUS_FOR_WORKS_AHEAD_OF_SCHEDULE = 'BonusForWorksAheadOfSchedule';
    const OTHER_BONUS = 'OtherBonus';
    const PROJECT_MANAGEMENT_COST = 'ProjectManagementCost';
    const PRO_RATA_RETENTION = 'ProRataRetention';
    const CONTRACTUAL_RETENTION = 'ContractualRetention';
    const OTHER_RETENTIONS = 'OtherRetentions';
    const INTEREST_ON_ARREARS = 'InterestOnArrears';
    const INTEREST = 'Interest';
    const CHARGE_PER_CREDIT_COVER = 'ChargePerCreditCover';
    const CHARGE_PER_UNUSED_CREDIT_COVER = 'ChargePerUnusedCreditCover';
    const MINIMUM_COMMISSION = 'MinimumCommission';
    const FACTORING_COMMISSION = 'FactoringCommission';
    const CHAMBER_OF_COMMERCE_CHARGE = 'ChamberOfCommerceCharge';
    const TRANSFER_CHARGES = 'TransferCharges';
    const REPATRIATION_CHARGES = 'RepatriationCharges';
    const MISCELLANEOUS_CHARGES = 'MiscellaneousCharges';
    const FOREIGN_EXCHANGE_CHARGES = 'ForeignExchangeCharges';
    const AGREED_DEBIT_INTEREST_CHARGE = 'AgreedDebitInterestCharge';
    const MANUFACTURERS_CONSUMER_DISCOUNT = 'ManufacturersConsumerDiscount';
    const FAX_ADVICE_CHARGE = 'FaxAdviceCharge';
    const DUE_TO_MILITARY_STATUS = 'DueToMilitaryStatus';
    const DUE_TO_WORK_ACCIDENT = 'DueToWorkAccident';
    const SPECIAL_AGREEMENT = 'SpecialAgreement';
    const PRODUCTION_ERROR_DISCOUNT = 'ProductionErrorDiscount';
    const NEW_OUTLET_DISCOUNT = 'NewOutletDiscount';
    const SAMPLE_DISCOUNT = 'SampleDiscount';
    const END_OF_RANGE_DISCOUNT = 'EndOfRangeDiscount';
    const CHARGE_FOR_A_CUSTOMER_SPECIFIC_FINISH = 'ChargeForACustomerSpecificFinish';
    const INCOTERM_DISCOUNT = 'IncotermDiscount';
    const POINT_OF_SALES_THRESHOLD_ALLOWANCE = 'PointOfSalesThresholdAllowance';
    const TECHNICAL_MODIFICATION_COSTS = 'TechnicalModificationCosts';
    const JOB_ORDER_PRODUCTION_COSTS = 'JobOrderProductionCosts';
    const OFF_PREMISES_COSTS = 'OffPremisesCosts';
    const ADDITIONAL_PROCESSING_COSTS = 'AdditionalProcessingCosts';
    const ATTESTING_CHARGE = 'AttestingCharge';
    const RUSH_DELIVERY_SURCHARGE = 'RushDeliverySurcharge';
    const SPECIAL_CONSTRUCTION_COSTS = 'SpecialConstructionCosts';
    const FREIGHT_CHARGES = 'FreightCharges';
    const PACKING_CHARGE = 'PackingCharge';
    const REPAIR_CHARGE = 'RepairCharge';
    const LOADING_CHARGE = 'LoadingCharge';
    const SETUP_CHARGE = 'SetupCharge';
    const TESTING_CHARGE = 'TestingCharge';
    const WAREHOUSING_CHARGE = 'WarehousingCharge';
    const GOLD_SURCHARGE = 'GoldSurcharge';
    const COPPER_SURCHARGE = 'CopperSurcharge';
    const MATERIAL_SURCHARGE_DEDUCTION = 'MaterialSurchargeDeduction';
    const LEAD_SURCHARGE = 'LeadSurcharge';
    const PRICE_INDEX_SURCHARGE = 'PriceIndexSurcharge';
    const PLATINUM_SURCHARGE = 'PlatinumSurcharge';
    const SILVER_SURCHARGE = 'SilverSurcharge';
    const WOLFRAM_SURCHARGE = 'WolframSurcharge';
    const ALUMINUM_SURCHARGE = 'AluminumSurcharge';
    const DISCOUNT = 'Discount';
    const INSURANCE = 'Insurance';
    const MINIMUM_ORDER_MINIMUM_BILLING_CHARGE = 'MinimumOrderMinimumBillingCharge';
    const MATERIAL_SURCHARGE_SPECIAL_MATERIALS = 'MaterialSurchargeSpecialMaterials';
    const SURCHARGE = 'Surcharge';
    const SPECIAL_REBATE = 'SpecialRebate';
    const CARBON_FOOTPRINT_CHARGE = 'CarbonFootprintCharge';
    const FIXED_LONG_TERM = 'FixedLongTerm';
    const TEMPORARY = 'Temporary';
    const STANDARD = 'Standard';
    const YEARLY_TURNOVER = 'YearlyTurnover';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::HANDLING_COMMISSION,
            self::AMENDMENT_COMMISSION,
            self::ACCEPTANCE_COMMISSION,
            self::COMMISSION_FOR_OBTAINING_ACCEPTANCE,
            self::COMMISSION_ON_DELIVERY,
            self::ADVISING_COMMISSION,
            self::CONFIRMATION_COMMISSION,
            self::DEFERRED_PAYMENT_COMMISSION,
            self::COMMISSION_FOR_TAKING_UP_DOCUMENTS,
            self::OPENING_COMMISSION,
            self::FEE_FOR_PAYMENT_UNDER_RESERVE,
            self::DISCREPANCY_FEE,
            self::DOMICILATION_COMMISSION,
            self::COMMISSION_FOR_RELEASE_OF_GOODS,
            self::COLLECTION_COMMISSION,
            self::NEGOTIATION_COMMISSION,
            self::RETURN_COMMISSION,
            self::BL_SPLITTING_CHARGES,
            self::TRUST_COMMISSION,
            self::TRANSFER_COMMISSION,
            self::COMMISSION_FOR_OPENING_IRREVOCABLE_DOCUMENTARY_CREDITS,
            self::PRE_ADVICE_COMMISSION,
            self::SUPERVISORY_COMMISSION,
            self::MODEL_CHARGES,
            self::RISK_COMMISSION,
            self::GUARANTEE_COMMISSION,
            self::REIMBURSEMENT_COMMISSION,
            self::STAMP_DUTY,
            self::BROKERAGE,
            self::BANK_CHARGES,
            self::BANK_CHARGES_INFORMATION,
            self::COURIER_FEE,
            self::PHONE_FEE,
            self::POSTAGE_FEE,
            self::SWIFT_FEE,
            self::TELEX_FEE,
            self::PENALTY_FOR_LATE_DELIVERY_OF_DOCUMENTS,
            self::PENALTY_FOR_LATE_DELIVERY_OF_VALUATION_OF_WORKS,
            self::PENALTY_FOR_EXECUTION_OF_WORKS_BEHIND_SCHEDULE,
            self::OTHER_PENALTIES,
            self::BONUS_FOR_WORKS_AHEAD_OF_SCHEDULE,
            self::OTHER_BONUS,
            self::PROJECT_MANAGEMENT_COST,
            self::PRO_RATA_RETENTION,
            self::CONTRACTUAL_RETENTION,
            self::OTHER_RETENTIONS,
            self::INTEREST_ON_ARREARS,
            self::INTEREST,
            self::CHARGE_PER_CREDIT_COVER,
            self::CHARGE_PER_UNUSED_CREDIT_COVER,
            self::MINIMUM_COMMISSION,
            self::FACTORING_COMMISSION,
            self::CHAMBER_OF_COMMERCE_CHARGE,
            self::TRANSFER_CHARGES,
            self::REPATRIATION_CHARGES,
            self::MISCELLANEOUS_CHARGES,
            self::FOREIGN_EXCHANGE_CHARGES,
            self::AGREED_DEBIT_INTEREST_CHARGE,
            self::MANUFACTURERS_CONSUMER_DISCOUNT,
            self::FAX_ADVICE_CHARGE,
            self::DUE_TO_MILITARY_STATUS,
            self::DUE_TO_WORK_ACCIDENT,
            self::SPECIAL_AGREEMENT,
            self::PRODUCTION_ERROR_DISCOUNT,
            self::NEW_OUTLET_DISCOUNT,
            self::SAMPLE_DISCOUNT,
            self::END_OF_RANGE_DISCOUNT,
            self::CHARGE_FOR_A_CUSTOMER_SPECIFIC_FINISH,
            self::INCOTERM_DISCOUNT,
            self::POINT_OF_SALES_THRESHOLD_ALLOWANCE,
            self::TECHNICAL_MODIFICATION_COSTS,
            self::JOB_ORDER_PRODUCTION_COSTS,
            self::OFF_PREMISES_COSTS,
            self::ADDITIONAL_PROCESSING_COSTS,
            self::ATTESTING_CHARGE,
            self::RUSH_DELIVERY_SURCHARGE,
            self::SPECIAL_CONSTRUCTION_COSTS,
            self::FREIGHT_CHARGES,
            self::PACKING_CHARGE,
            self::REPAIR_CHARGE,
            self::LOADING_CHARGE,
            self::SETUP_CHARGE,
            self::TESTING_CHARGE,
            self::WAREHOUSING_CHARGE,
            self::GOLD_SURCHARGE,
            self::COPPER_SURCHARGE,
            self::MATERIAL_SURCHARGE_DEDUCTION,
            self::LEAD_SURCHARGE,
            self::PRICE_INDEX_SURCHARGE,
            self::PLATINUM_SURCHARGE,
            self::SILVER_SURCHARGE,
            self::WOLFRAM_SURCHARGE,
            self::ALUMINUM_SURCHARGE,
            self::DISCOUNT,
            self::INSURANCE,
            self::MINIMUM_ORDER_MINIMUM_BILLING_CHARGE,
            self::MATERIAL_SURCHARGE_SPECIAL_MATERIALS,
            self::SURCHARGE,
            self::SPECIAL_REBATE,
            self::CARBON_FOOTPRINT_CHARGE,
            self::FIXED_LONG_TERM,
            self::TEMPORARY,
            self::STANDARD,
            self::YEARLY_TURNOVER,
        ];
    }
}


