<?php
/**
 * AttachmentMimeType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dangl\AVACloud\Model;
use \Dangl\AVACloud\ObjectSerializer;

/**
 * AttachmentMimeType Class Doc Comment
 *
 * @category Class
 * @description Describes a mime type of a document
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AttachmentMimeType
{
    /**
     * Possible values of this enum
     */
    public const UNKNOWN = 'Unknown';

    public const PDF = 'Pdf';

    public const PNG = 'Png';

    public const JPEG = 'Jpeg';

    public const CSV = 'Csv';

    public const EXCEL = 'Excel';

    public const OPEN_OFFICE_SPREADSHEET = 'OpenOfficeSpreadsheet';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::PDF,
            self::PNG,
            self::JPEG,
            self::CSV,
            self::EXCEL,
            self::OPEN_OFFICE_SPREADSHEET
        ];
    }
}


