<?php
/**
 * CommercePropertiesDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dangl\AVACloud\Model;

use \ArrayAccess;
use \Dangl\AVACloud\ObjectSerializer;

/**
 * CommercePropertiesDto Class Doc Comment
 *
 * @category Class
 * @description This class holds specialized information that is relevant to trade or commerce based data exchange scenarios, e.g. between customers, vendors, suppliers and distributors. It is used when exporting to GAEB XML 9x exchange phases.
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CommercePropertiesDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CommercePropertiesDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'article_number' => 'string',
        'ean_gtin_article_number' => 'string',
        'iln_article_number' => 'string',
        'catalogue_number' => 'string',
        'catalogue_article_number' => 'string',
        'price_basis' => 'float',
        'sub_position_identifier' => 'string',
        'customer_base_item_number' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'article_number' => null,
        'ean_gtin_article_number' => null,
        'iln_article_number' => null,
        'catalogue_number' => null,
        'catalogue_article_number' => null,
        'price_basis' => 'decimal',
        'sub_position_identifier' => null,
        'customer_base_item_number' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'article_number' => false,
        'ean_gtin_article_number' => false,
        'iln_article_number' => false,
        'catalogue_number' => false,
        'catalogue_article_number' => false,
        'price_basis' => false,
        'sub_position_identifier' => false,
        'customer_base_item_number' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'article_number' => 'articleNumber',
        'ean_gtin_article_number' => 'eanGtinArticleNumber',
        'iln_article_number' => 'ilnArticleNumber',
        'catalogue_number' => 'catalogueNumber',
        'catalogue_article_number' => 'catalogueArticleNumber',
        'price_basis' => 'priceBasis',
        'sub_position_identifier' => 'subPositionIdentifier',
        'customer_base_item_number' => 'customerBaseItemNumber'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'article_number' => 'setArticleNumber',
        'ean_gtin_article_number' => 'setEanGtinArticleNumber',
        'iln_article_number' => 'setIlnArticleNumber',
        'catalogue_number' => 'setCatalogueNumber',
        'catalogue_article_number' => 'setCatalogueArticleNumber',
        'price_basis' => 'setPriceBasis',
        'sub_position_identifier' => 'setSubPositionIdentifier',
        'customer_base_item_number' => 'setCustomerBaseItemNumber'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'article_number' => 'getArticleNumber',
        'ean_gtin_article_number' => 'getEanGtinArticleNumber',
        'iln_article_number' => 'getIlnArticleNumber',
        'catalogue_number' => 'getCatalogueNumber',
        'catalogue_article_number' => 'getCatalogueArticleNumber',
        'price_basis' => 'getPriceBasis',
        'sub_position_identifier' => 'getSubPositionIdentifier',
        'customer_base_item_number' => 'getCustomerBaseItemNumber'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('article_number', $data ?? [], null);
        $this->setIfExists('ean_gtin_article_number', $data ?? [], null);
        $this->setIfExists('iln_article_number', $data ?? [], null);
        $this->setIfExists('catalogue_number', $data ?? [], null);
        $this->setIfExists('catalogue_article_number', $data ?? [], null);
        $this->setIfExists('price_basis', $data ?? [], null);
        $this->setIfExists('sub_position_identifier', $data ?? [], null);
        $this->setIfExists('customer_base_item_number', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets article_number
     *
     * @return string|null
     */
    public function getArticleNumber()
    {
        return $this->container['article_number'];
    }

    /**
     * Sets article_number
     *
     * @param string|null $article_number This maps to ArtNo in GAEB XML and represents an article number given by the supplier.
     *
     * @return self
     */
    public function setArticleNumber($article_number)
    {
        if (is_null($article_number)) {
            throw new \InvalidArgumentException('non-nullable article_number cannot be null');
        }
        $this->container['article_number'] = $article_number;

        return $this;
    }

    /**
     * Gets ean_gtin_article_number
     *
     * @return string|null
     */
    public function getEanGtinArticleNumber()
    {
        return $this->container['ean_gtin_article_number'];
    }

    /**
     * Sets ean_gtin_article_number
     *
     * @param string|null $ean_gtin_article_number This maps to EAN in GAEB XML and represents an GTIN (formerly EAN) article number.
     *
     * @return self
     */
    public function setEanGtinArticleNumber($ean_gtin_article_number)
    {
        if (is_null($ean_gtin_article_number)) {
            throw new \InvalidArgumentException('non-nullable ean_gtin_article_number cannot be null');
        }
        $this->container['ean_gtin_article_number'] = $ean_gtin_article_number;

        return $this;
    }

    /**
     * Gets iln_article_number
     *
     * @return string|null
     */
    public function getIlnArticleNumber()
    {
        return $this->container['iln_article_number'];
    }

    /**
     * Sets iln_article_number
     *
     * @param string|null $iln_article_number This maps to ArtNoID in GAEB XML and represents an ILN article number.
     *
     * @return self
     */
    public function setIlnArticleNumber($iln_article_number)
    {
        if (is_null($iln_article_number)) {
            throw new \InvalidArgumentException('non-nullable iln_article_number cannot be null');
        }
        $this->container['iln_article_number'] = $iln_article_number;

        return $this;
    }

    /**
     * Gets catalogue_number
     *
     * @return string|null
     */
    public function getCatalogueNumber()
    {
        return $this->container['catalogue_number'];
    }

    /**
     * Sets catalogue_number
     *
     * @param string|null $catalogue_number This maps to CatalogNo in GAEB XML and represents an identifier of a specific catalogue. The referenced catalogue is usually a customer specific one, not related to CatalogueReferences.
     *
     * @return self
     */
    public function setCatalogueNumber($catalogue_number)
    {
        if (is_null($catalogue_number)) {
            throw new \InvalidArgumentException('non-nullable catalogue_number cannot be null');
        }
        $this->container['catalogue_number'] = $catalogue_number;

        return $this;
    }

    /**
     * Gets catalogue_article_number
     *
     * @return string|null
     */
    public function getCatalogueArticleNumber()
    {
        return $this->container['catalogue_article_number'];
    }

    /**
     * Sets catalogue_article_number
     *
     * @param string|null $catalogue_article_number This maps to CatalogArtNo in GAEB XML and represents a key that maps to an entry in a specific catalogue. The referenced catalogue is usually a customer specific one, not related to CatalogueReferences.
     *
     * @return self
     */
    public function setCatalogueArticleNumber($catalogue_article_number)
    {
        if (is_null($catalogue_article_number)) {
            throw new \InvalidArgumentException('non-nullable catalogue_article_number cannot be null');
        }
        $this->container['catalogue_article_number'] = $catalogue_article_number;

        return $this;
    }

    /**
     * Gets price_basis
     *
     * @return float|null
     */
    public function getPriceBasis()
    {
        return $this->container['price_basis'];
    }

    /**
     * Sets price_basis
     *
     * @param float|null $price_basis This optional property can be used to indicate the basis for prices for a single position. Price basis means that the price is given per unit of the basis, e.g. per a pack of five when this property is set to '5'.
     *
     * @return self
     */
    public function setPriceBasis($price_basis)
    {
        if (is_null($price_basis)) {
            throw new \InvalidArgumentException('non-nullable price_basis cannot be null');
        }
        $this->container['price_basis'] = $price_basis;

        return $this;
    }

    /**
     * Gets sub_position_identifier
     *
     * @return string|null
     */
    public function getSubPositionIdentifier()
    {
        return $this->container['sub_position_identifier'];
    }

    /**
     * Sets sub_position_identifier
     *
     * @param string|null $sub_position_identifier This optional property can be used to indicate a sub position identifier specific for the commerce exchange
     *
     * @return self
     */
    public function setSubPositionIdentifier($sub_position_identifier)
    {
        if (is_null($sub_position_identifier)) {
            throw new \InvalidArgumentException('non-nullable sub_position_identifier cannot be null');
        }
        $this->container['sub_position_identifier'] = $sub_position_identifier;

        return $this;
    }

    /**
     * Gets customer_base_item_number
     *
     * @return string|null
     */
    public function getCustomerBaseItemNumber()
    {
        return $this->container['customer_base_item_number'];
    }

    /**
     * Sets customer_base_item_number
     *
     * @param string|null $customer_base_item_number In a commerce exchange, this property is usually used to reference the base item number of an underlying phase 83 exchange file
     *
     * @return self
     */
    public function setCustomerBaseItemNumber($customer_base_item_number)
    {
        if (is_null($customer_base_item_number)) {
            throw new \InvalidArgumentException('non-nullable customer_base_item_number cannot be null');
        }
        $this->container['customer_base_item_number'] = $customer_base_item_number;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


