<?php
/**
 * DestinationGaebExchangePhase
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dangl\AVACloud\Model;
use \Dangl\AVACloud\ObjectSerializer;

/**
 * DestinationGaebExchangePhase Class Doc Comment
 *
 * @category Class
 * @description The GAEB exchange phase to transform to. The phases are: Base &#x3D; 81 CostEstimate &#x3D; 82 OfferRequest &#x3D; 83 Offer &#x3D; 84 SideOffer &#x3D; 85 Grant &#x3D; 86
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DestinationGaebExchangePhase
{
    /**
     * Possible values of this enum
     */
    public const NONE = 'None';

    public const BASE = 'Base';

    public const OFFER_REQUEST = 'OfferRequest';

    public const OFFER = 'Offer';

    public const GRANT = 'Grant';

    public const COST_ESTIMATE = 'CostEstimate';

    public const SIDE_OFFER = 'SideOffer';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::BASE,
            self::OFFER_REQUEST,
            self::OFFER,
            self::GRANT,
            self::COST_ESTIMATE,
            self::SIDE_OFFER
        ];
    }
}


