<?php
/**
 * ExchangePhaseDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dangl\AVACloud\Model;
use \Dangl\AVACloud\ObjectSerializer;

/**
 * ExchangePhaseDto Class Doc Comment
 *
 * @category Class
 * @description Indicates a ServiceSpecification&#39;s exchange phase, based on the GAEB exchange phases.
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExchangePhaseDto
{
    /**
     * Possible values of this enum
     */
    public const UNDEFINED = 'Undefined';

    public const BASE = 'Base';

    public const COST_ESTIMATE = 'CostEstimate';

    public const OFFER_REQUEST = 'OfferRequest';

    public const OFFER = 'Offer';

    public const SIDE_OFFER = 'SideOffer';

    public const GRANT = 'Grant';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNDEFINED,
            self::BASE,
            self::COST_ESTIMATE,
            self::OFFER_REQUEST,
            self::OFFER,
            self::SIDE_OFFER,
            self::GRANT
        ];
    }
}


