<?php
/**
 * HoldOutDurationUnitDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dangl\AVACloud\Model;
use \Dangl\AVACloud\ObjectSerializer;

/**
 * HoldOutDurationUnitDto Class Doc Comment
 *
 * @category Class
 * @description Duration used in retention positions
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HoldOutDurationUnitDto
{
    /**
     * Possible values of this enum
     */
    public const UNKNOWN = 'Unknown';

    public const MINUTES = 'Minutes';

    public const HOURS = 'Hours';

    public const DAYS = 'Days';

    public const WEEKS = 'Weeks';

    public const MONTHS = 'Months';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::MINUTES,
            self::HOURS,
            self::DAYS,
            self::WEEKS,
            self::MONTHS
        ];
    }
}


