<?php
/**
 * ItemNumberSchemaTierDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dangl\AVACloud\Model;

use \ArrayAccess;
use \Dangl\AVACloud\ObjectSerializer;

/**
 * ItemNumberSchemaTierDto Class Doc Comment
 *
 * @category Class
 * @description Represents information about a single Tier in an ItemNumber.
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ItemNumberSchemaTierDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ItemNumberSchemaTierDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'length' => 'int',
        'type' => '\Dangl\AVACloud\Model\ItemNumberTypeDto',
        'alignment' => '\Dangl\AVACloud\Model\ItemNumberSchemaTierAlignmentDto',
        'tierType' => '\Dangl\AVACloud\Model\ItemNumberSchemaTierTypeDto',
        'isLot' => 'bool',
        'increment' => 'int',
        'tierName' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'length' => 'int32',
        'type' => null,
        'alignment' => null,
        'tierType' => null,
        'isLot' => null,
        'increment' => 'int32',
        'tierName' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'length' => false,
        'type' => false,
        'alignment' => false,
        'tierType' => false,
        'isLot' => false,
        'increment' => false,
        'tierName' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'length' => 'length',
        'type' => 'type',
        'alignment' => 'alignment',
        'tierType' => 'tierType',
        'isLot' => 'isLot',
        'increment' => 'increment',
        'tierName' => 'tierName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'length' => 'setLength',
        'type' => 'setType',
        'alignment' => 'setAlignment',
        'tierType' => 'setTierType',
        'isLot' => 'setIsLot',
        'increment' => 'setIncrement',
        'tierName' => 'setTierName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'length' => 'getLength',
        'type' => 'getType',
        'alignment' => 'getAlignment',
        'tierType' => 'getTierType',
        'isLot' => 'getIsLot',
        'increment' => 'getIncrement',
        'tierName' => 'getTierName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('length', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('alignment', $data ?? [], null);
        $this->setIfExists('tierType', $data ?? [], null);
        $this->setIfExists('isLot', $data ?? [], null);
        $this->setIfExists('increment', $data ?? [], null);
        $this->setIfExists('tierName', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['length'] === null) {
            $invalidProperties[] = "'length' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['tierType'] === null) {
            $invalidProperties[] = "'tierType' can't be null";
        }
        if ($this->container['isLot'] === null) {
            $invalidProperties[] = "'isLot' can't be null";
        }
        if ($this->container['increment'] === null) {
            $invalidProperties[] = "'increment' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets length
     *
     * @return int
     */
    public function getLength()
    {
        return $this->container['length'];
    }

    /**
     * Sets length
     *
     * @param int $length The (maximum) length for this tier. Will not accept a length less than 1. Defaults to 1 if length less than one is specified.
     *
     * @return self
     */
    public function setLength($length)
    {
        if (is_null($length)) {
            throw new \InvalidArgumentException('non-nullable length cannot be null');
        }
        $this->container['length'] = $length;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \Dangl\AVACloud\Model\ItemNumberTypeDto
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \Dangl\AVACloud\Model\ItemNumberTypeDto $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets alignment
     *
     * @return \Dangl\AVACloud\Model\ItemNumberSchemaTierAlignmentDto|null
     */
    public function getAlignment()
    {
        return $this->container['alignment'];
    }

    /**
     * Sets alignment
     *
     * @param \Dangl\AVACloud\Model\ItemNumberSchemaTierAlignmentDto|null $alignment alignment
     *
     * @return self
     */
    public function setAlignment($alignment)
    {
        if (is_null($alignment)) {
            throw new \InvalidArgumentException('non-nullable alignment cannot be null');
        }
        $this->container['alignment'] = $alignment;

        return $this;
    }

    /**
     * Gets tierType
     *
     * @return \Dangl\AVACloud\Model\ItemNumberSchemaTierTypeDto
     */
    public function getTierType()
    {
        return $this->container['tierType'];
    }

    /**
     * Sets tierType
     *
     * @param \Dangl\AVACloud\Model\ItemNumberSchemaTierTypeDto $tierType tierType
     *
     * @return self
     */
    public function setTierType($tierType)
    {
        if (is_null($tierType)) {
            throw new \InvalidArgumentException('non-nullable tierType cannot be null');
        }
        $this->container['tierType'] = $tierType;

        return $this;
    }

    /**
     * Gets isLot
     *
     * @return bool
     */
    public function getIsLot()
    {
        return $this->container['isLot'];
    }

    /**
     * Sets isLot
     *
     * @param bool $isLot Indicates if this tier represents a lot. See the documentation for more information about lots.
     *
     * @return self
     */
    public function setIsLot($isLot)
    {
        if (is_null($isLot)) {
            throw new \InvalidArgumentException('non-nullable isLot cannot be null');
        }
        $this->container['isLot'] = $isLot;

        return $this;
    }

    /**
     * Gets increment
     *
     * @return int
     */
    public function getIncrement()
    {
        return $this->container['increment'];
    }

    /**
     * Sets increment
     *
     * @param int $increment This value is the increment, or step size, that should be used for new item numbers. It defaults to DEFAULT_INCREMENT, but can be changed to any other positive number greater than zero. Invalid values make this be set to one '1'
     *
     * @return self
     */
    public function setIncrement($increment)
    {
        if (is_null($increment)) {
            throw new \InvalidArgumentException('non-nullable increment cannot be null');
        }
        $this->container['increment'] = $increment;

        return $this;
    }

    /**
     * Gets tierName
     *
     * @return string|null
     */
    public function getTierName()
    {
        return $this->container['tierName'];
    }

    /**
     * Sets tierName
     *
     * @param string|null $tierName This is an optional name for the given tier
     *
     * @return self
     */
    public function setTierName($tierName)
    {
        if (is_null($tierName)) {
            throw new \InvalidArgumentException('non-nullable tierName cannot be null');
        }
        $this->container['tierName'] = $tierName;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


