<?php
/**
 * LineItemAllowance
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dangl\AVACloud\Model;

use \ArrayAccess;
use \Dangl\AVACloud\ObjectSerializer;

/**
 * LineItemAllowance Class Doc Comment
 *
 * @category Class
 * @description Allowance for a single line item
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LineItemAllowance implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LineItemAllowance';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'netAmount' => 'float',
        'relativeAllowanceBaseAmount' => 'float',
        'relativeAllowancePercentage' => 'float',
        'reason' => 'string',
        'reasonCode' => 'string',
        'reasonType' => '\Dangl\AVACloud\Model\AllowanceReasonType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'netAmount' => 'decimal',
        'relativeAllowanceBaseAmount' => 'decimal',
        'relativeAllowancePercentage' => 'decimal',
        'reason' => null,
        'reasonCode' => null,
        'reasonType' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'netAmount' => false,
        'relativeAllowanceBaseAmount' => false,
        'relativeAllowancePercentage' => false,
        'reason' => false,
        'reasonCode' => false,
        'reasonType' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'netAmount' => 'netAmount',
        'relativeAllowanceBaseAmount' => 'relativeAllowanceBaseAmount',
        'relativeAllowancePercentage' => 'relativeAllowancePercentage',
        'reason' => 'reason',
        'reasonCode' => 'reasonCode',
        'reasonType' => 'reasonType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'netAmount' => 'setNetAmount',
        'relativeAllowanceBaseAmount' => 'setRelativeAllowanceBaseAmount',
        'relativeAllowancePercentage' => 'setRelativeAllowancePercentage',
        'reason' => 'setReason',
        'reasonCode' => 'setReasonCode',
        'reasonType' => 'setReasonType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'netAmount' => 'getNetAmount',
        'relativeAllowanceBaseAmount' => 'getRelativeAllowanceBaseAmount',
        'relativeAllowancePercentage' => 'getRelativeAllowancePercentage',
        'reason' => 'getReason',
        'reasonCode' => 'getReasonCode',
        'reasonType' => 'getReasonType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('netAmount', $data ?? [], null);
        $this->setIfExists('relativeAllowanceBaseAmount', $data ?? [], null);
        $this->setIfExists('relativeAllowancePercentage', $data ?? [], null);
        $this->setIfExists('reason', $data ?? [], null);
        $this->setIfExists('reasonCode', $data ?? [], null);
        $this->setIfExists('reasonType', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets netAmount
     *
     * @return float|null
     */
    public function getNetAmount()
    {
        return $this->container['netAmount'];
    }

    /**
     * Sets netAmount
     *
     * @param float|null $netAmount BT-136 The net amount of the allowance
     *
     * @return self
     */
    public function setNetAmount($netAmount)
    {
        if (is_null($netAmount)) {
            throw new \InvalidArgumentException('non-nullable netAmount cannot be null');
        }
        $this->container['netAmount'] = $netAmount;

        return $this;
    }

    /**
     * Gets relativeAllowanceBaseAmount
     *
     * @return float|null
     */
    public function getRelativeAllowanceBaseAmount()
    {
        return $this->container['relativeAllowanceBaseAmount'];
    }

    /**
     * Sets relativeAllowanceBaseAmount
     *
     * @param float|null $relativeAllowanceBaseAmount BT-137 If this is a relative / percentage allowance, this should be set and give the base amount that is being used for the calculation
     *
     * @return self
     */
    public function setRelativeAllowanceBaseAmount($relativeAllowanceBaseAmount)
    {
        if (is_null($relativeAllowanceBaseAmount)) {
            throw new \InvalidArgumentException('non-nullable relativeAllowanceBaseAmount cannot be null');
        }
        $this->container['relativeAllowanceBaseAmount'] = $relativeAllowanceBaseAmount;

        return $this;
    }

    /**
     * Gets relativeAllowancePercentage
     *
     * @return float|null
     */
    public function getRelativeAllowancePercentage()
    {
        return $this->container['relativeAllowancePercentage'];
    }

    /**
     * Sets relativeAllowancePercentage
     *
     * @param float|null $relativeAllowancePercentage BT-138 If this is a relative / percentage allowance, this should be set and be given in decimal representation, meaning 19% would be 0.19
     *
     * @return self
     */
    public function setRelativeAllowancePercentage($relativeAllowancePercentage)
    {
        if (is_null($relativeAllowancePercentage)) {
            throw new \InvalidArgumentException('non-nullable relativeAllowancePercentage cannot be null');
        }
        $this->container['relativeAllowancePercentage'] = $relativeAllowancePercentage;

        return $this;
    }

    /**
     * Gets reason
     *
     * @return string|null
     */
    public function getReason()
    {
        return $this->container['reason'];
    }

    /**
     * Sets reason
     *
     * @param string|null $reason BT-139 A description of the allowance.
     *
     * @return self
     */
    public function setReason($reason)
    {
        if (is_null($reason)) {
            throw new \InvalidArgumentException('non-nullable reason cannot be null');
        }
        $this->container['reason'] = $reason;

        return $this;
    }

    /**
     * Gets reasonCode
     *
     * @return string|null
     */
    public function getReasonCode()
    {
        return $this->container['reasonCode'];
    }

    /**
     * Sets reasonCode
     *
     * @param string|null $reasonCode BT-140 A reason code for the allowance according to UNTDID 5189. Should be a code from this list: https://unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred5189.htm
     *
     * @return self
     */
    public function setReasonCode($reasonCode)
    {
        if (is_null($reasonCode)) {
            throw new \InvalidArgumentException('non-nullable reasonCode cannot be null');
        }
        $this->container['reasonCode'] = $reasonCode;

        return $this;
    }

    /**
     * Gets reasonType
     *
     * @return \Dangl\AVACloud\Model\AllowanceReasonType|null
     */
    public function getReasonType()
    {
        return $this->container['reasonType'];
    }

    /**
     * Sets reasonType
     *
     * @param \Dangl\AVACloud\Model\AllowanceReasonType|null $reasonType reasonType
     *
     * @return self
     */
    public function setReasonType($reasonType)
    {
        if (is_null($reasonType)) {
            throw new \InvalidArgumentException('non-nullable reasonType cannot be null');
        }
        $this->container['reasonType'] = $reasonType;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


