<?php
/**
 * LineItemPriceDetail
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dangl\AVACloud\Model;

use \ArrayAccess;
use \Dangl\AVACloud\ObjectSerializer;

/**
 * LineItemPriceDetail Class Doc Comment
 *
 * @category Class
 * @description Price details about a line item
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LineItemPriceDetail implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LineItemPriceDetail';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'net_price' => 'float',
        'absolute_discount_per_item' => 'float',
        'gross_price' => 'float',
        'base_quantity' => 'float',
        'base_quantity_unit_code' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'net_price' => 'decimal',
        'absolute_discount_per_item' => 'decimal',
        'gross_price' => 'decimal',
        'base_quantity' => 'decimal',
        'base_quantity_unit_code' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'net_price' => false,
        'absolute_discount_per_item' => false,
        'gross_price' => false,
        'base_quantity' => false,
        'base_quantity_unit_code' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'net_price' => 'netPrice',
        'absolute_discount_per_item' => 'absoluteDiscountPerItem',
        'gross_price' => 'grossPrice',
        'base_quantity' => 'baseQuantity',
        'base_quantity_unit_code' => 'baseQuantityUnitCode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'net_price' => 'setNetPrice',
        'absolute_discount_per_item' => 'setAbsoluteDiscountPerItem',
        'gross_price' => 'setGrossPrice',
        'base_quantity' => 'setBaseQuantity',
        'base_quantity_unit_code' => 'setBaseQuantityUnitCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'net_price' => 'getNetPrice',
        'absolute_discount_per_item' => 'getAbsoluteDiscountPerItem',
        'gross_price' => 'getGrossPrice',
        'base_quantity' => 'getBaseQuantity',
        'base_quantity_unit_code' => 'getBaseQuantityUnitCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('net_price', $data ?? [], null);
        $this->setIfExists('absolute_discount_per_item', $data ?? [], null);
        $this->setIfExists('gross_price', $data ?? [], null);
        $this->setIfExists('base_quantity', $data ?? [], null);
        $this->setIfExists('base_quantity_unit_code', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets net_price
     *
     * @return float|null
     */
    public function getNetPrice()
    {
        return $this->container['net_price'];
    }

    /**
     * Sets net_price
     *
     * @param float|null $net_price BT-146 The net price of this line item. This is the unit price
     *
     * @return self
     */
    public function setNetPrice($net_price)
    {
        if (is_null($net_price)) {
            throw new \InvalidArgumentException('non-nullable net_price cannot be null');
        }
        $this->container['net_price'] = $net_price;

        return $this;
    }

    /**
     * Gets absolute_discount_per_item
     *
     * @return float|null
     */
    public function getAbsoluteDiscountPerItem()
    {
        return $this->container['absolute_discount_per_item'];
    }

    /**
     * Sets absolute_discount_per_item
     *
     * @param float|null $absolute_discount_per_item BT-147 A discount for this line item, given as an absolute value. It is essentially the difference between NetPrice (or the list price) and the actual invoiced price GrossPrice.
     *
     * @return self
     */
    public function setAbsoluteDiscountPerItem($absolute_discount_per_item)
    {
        if (is_null($absolute_discount_per_item)) {
            throw new \InvalidArgumentException('non-nullable absolute_discount_per_item cannot be null');
        }
        $this->container['absolute_discount_per_item'] = $absolute_discount_per_item;

        return $this;
    }

    /**
     * Gets gross_price
     *
     * @return float|null
     */
    public function getGrossPrice()
    {
        return $this->container['gross_price'];
    }

    /**
     * Sets gross_price
     *
     * @param float|null $gross_price BT-148 The gross price of this line item, meaning the price without taxes that will be invoiced
     *
     * @return self
     */
    public function setGrossPrice($gross_price)
    {
        if (is_null($gross_price)) {
            throw new \InvalidArgumentException('non-nullable gross_price cannot be null');
        }
        $this->container['gross_price'] = $gross_price;

        return $this;
    }

    /**
     * Gets base_quantity
     *
     * @return float|null
     */
    public function getBaseQuantity()
    {
        return $this->container['base_quantity'];
    }

    /**
     * Sets base_quantity
     *
     * @param float|null $base_quantity BT-149 The quantity for which this price is valid. In combination with the NetPrice, you basically specify the denominator of the unit price for a line item.
     *
     * @return self
     */
    public function setBaseQuantity($base_quantity)
    {
        if (is_null($base_quantity)) {
            throw new \InvalidArgumentException('non-nullable base_quantity cannot be null');
        }
        $this->container['base_quantity'] = $base_quantity;

        return $this;
    }

    /**
     * Gets base_quantity_unit_code
     *
     * @return string|null
     */
    public function getBaseQuantityUnitCode()
    {
        return $this->container['base_quantity_unit_code'];
    }

    /**
     * Sets base_quantity_unit_code
     *
     * @param string|null $base_quantity_unit_code BT-150 A code representing the unit for the base quantity
     *
     * @return self
     */
    public function setBaseQuantityUnitCode($base_quantity_unit_code)
    {
        if (is_null($base_quantity_unit_code)) {
            throw new \InvalidArgumentException('non-nullable base_quantity_unit_code cannot be null');
        }
        $this->container['base_quantity_unit_code'] = $base_quantity_unit_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


