<?php
/**
 * OenormOriginCodeDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dangl\AVACloud\Model;
use \Dangl\AVACloud\ObjectSerializer;

/**
 * OenormOriginCodeDto Class Doc Comment
 *
 * @category Class
 * @description This indicates where the content of this element originates, if set. It corresponds to &#39;herkunftskennzeichen&#39; in ÖNorm
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OenormOriginCodeDto
{
    /**
     * Possible values of this enum
     */
    public const UNKNOWN = 'Unknown';

    public const FREE_TEXT = 'FreeText';

    public const ADDITION_DESCRIPTION = 'AdditionDescription';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::FREE_TEXT,
            self::ADDITION_DESCRIPTION
        ];
    }
}


