<?php
/**
 * PositionComplementingTypeDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dangl\AVACloud\Model;
use \Dangl\AVACloud\ObjectSerializer;

/**
 * PositionComplementingTypeDto Class Doc Comment
 *
 * @category Class
 * @description This enum represents the different ways in which a complementing position type can be specified. It is typically only used in GAEB exports, since in Dangl.AVA, complementing positions are always explicitly referenced.
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PositionComplementingTypeDto
{
    /**
     * Possible values of this enum
     */
    public const UNDEFINED = 'Undefined';

    public const ALL_PREVIOUS_MARKED_POSITIONS = 'AllPreviousMarkedPositions';

    public const ALL_PREVIOUS_POSITIONS = 'AllPreviousPositions';

    public const REFERENCED_POSITIONS = 'ReferencedPositions';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNDEFINED,
            self::ALL_PREVIOUS_MARKED_POSITIONS,
            self::ALL_PREVIOUS_POSITIONS,
            self::REFERENCED_POSITIONS
        ];
    }
}


