<?php
/**
 * ServiceSpecificationGroupDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dangl\AVACloud\Model;
use \Dangl\AVACloud\ObjectSerializer;

/**
 * ServiceSpecificationGroupDto Class Doc Comment
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ServiceSpecificationGroupDto extends IElementDto
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ServiceSpecificationGroupDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'project_hourly_wage' => 'float',
        'project_tax_rate' => 'float',
        'project_price_components' => 'string[]',
        'project_item_number_schema' => '\Dangl\AVACloud\Model\ItemNumberSchemaDto',
        'elements' => '\Dangl\AVACloud\Model\IElementDto[]',
        'project_labour_time_label' => 'string',
        'contains_duplicate_item_numbers' => 'bool',
        'contains_duplicate_element_ids' => 'bool',
        'ignore_duplicate_item_numbers' => 'bool',
        'ignore_project_catalogue_propagation' => 'bool',
        'ignore_duplicate_element_ids' => 'bool',
        'total_price_gross_by_tax_rate' => '\Dangl\AVACloud\Model\GrossPriceComponentDto[]',
        'ignore_child_price_updates' => 'bool',
        'deducted_price' => 'float',
        'deduction_factor' => 'float',
        'absolute_deduction' => 'float',
        'total_price' => 'float',
        'total_price_gross' => 'float',
        'total_price_gross_deducted' => 'float',
        'price_type' => '\Dangl\AVACloud\Model\PriceTypeDto',
        'short_text' => 'string',
        'comission_status' => '\Dangl\AVACloud\Model\ComissionStatusDto',
        'item_number' => '\Dangl\AVACloud\Model\ItemNumberDto',
        'element_type' => 'string',
        'is_lot' => 'bool',
        'alternative_to' => 'string',
        'oenorm_properties' => '\Dangl\AVACloud\Model\OenormPropertiesDto',
        'hierarchy_level' => 'int',
        'addendum_status' => '\Dangl\AVACloud\Model\AddendumStatusDto',
        'alternative_identifier' => 'int',
        'alternative_group_identifier' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'project_hourly_wage' => 'decimal',
        'project_tax_rate' => 'decimal',
        'project_price_components' => null,
        'project_item_number_schema' => null,
        'elements' => null,
        'project_labour_time_label' => null,
        'contains_duplicate_item_numbers' => null,
        'contains_duplicate_element_ids' => null,
        'ignore_duplicate_item_numbers' => null,
        'ignore_project_catalogue_propagation' => null,
        'ignore_duplicate_element_ids' => null,
        'total_price_gross_by_tax_rate' => null,
        'ignore_child_price_updates' => null,
        'deducted_price' => 'decimal',
        'deduction_factor' => 'decimal',
        'absolute_deduction' => 'decimal',
        'total_price' => 'decimal',
        'total_price_gross' => 'decimal',
        'total_price_gross_deducted' => 'decimal',
        'price_type' => null,
        'short_text' => null,
        'comission_status' => null,
        'item_number' => null,
        'element_type' => null,
        'is_lot' => null,
        'alternative_to' => 'guid',
        'oenorm_properties' => null,
        'hierarchy_level' => 'int32',
        'addendum_status' => null,
        'alternative_identifier' => 'int32',
        'alternative_group_identifier' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'project_hourly_wage' => false,
        'project_tax_rate' => false,
        'project_price_components' => false,
        'project_item_number_schema' => false,
        'elements' => false,
        'project_labour_time_label' => false,
        'contains_duplicate_item_numbers' => false,
        'contains_duplicate_element_ids' => false,
        'ignore_duplicate_item_numbers' => false,
        'ignore_project_catalogue_propagation' => false,
        'ignore_duplicate_element_ids' => false,
        'total_price_gross_by_tax_rate' => false,
        'ignore_child_price_updates' => false,
        'deducted_price' => false,
        'deduction_factor' => false,
        'absolute_deduction' => false,
        'total_price' => false,
        'total_price_gross' => false,
        'total_price_gross_deducted' => false,
        'price_type' => false,
        'short_text' => false,
        'comission_status' => false,
        'item_number' => false,
        'element_type' => false,
        'is_lot' => false,
        'alternative_to' => false,
        'oenorm_properties' => false,
        'hierarchy_level' => false,
        'addendum_status' => false,
        'alternative_identifier' => false,
        'alternative_group_identifier' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes + parent::openAPITypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats + parent::openAPIFormats();
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables + parent::openAPINullables();
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'project_hourly_wage' => 'projectHourlyWage',
        'project_tax_rate' => 'projectTaxRate',
        'project_price_components' => 'projectPriceComponents',
        'project_item_number_schema' => 'projectItemNumberSchema',
        'elements' => 'elements',
        'project_labour_time_label' => 'projectLabourTimeLabel',
        'contains_duplicate_item_numbers' => 'containsDuplicateItemNumbers',
        'contains_duplicate_element_ids' => 'containsDuplicateElementIds',
        'ignore_duplicate_item_numbers' => 'ignoreDuplicateItemNumbers',
        'ignore_project_catalogue_propagation' => 'ignoreProjectCataloguePropagation',
        'ignore_duplicate_element_ids' => 'ignoreDuplicateElementIds',
        'total_price_gross_by_tax_rate' => 'totalPriceGrossByTaxRate',
        'ignore_child_price_updates' => 'ignoreChildPriceUpdates',
        'deducted_price' => 'deductedPrice',
        'deduction_factor' => 'deductionFactor',
        'absolute_deduction' => 'absoluteDeduction',
        'total_price' => 'totalPrice',
        'total_price_gross' => 'totalPriceGross',
        'total_price_gross_deducted' => 'totalPriceGrossDeducted',
        'price_type' => 'priceType',
        'short_text' => 'shortText',
        'comission_status' => 'comissionStatus',
        'item_number' => 'itemNumber',
        'element_type' => 'elementType',
        'is_lot' => 'isLot',
        'alternative_to' => 'alternativeTo',
        'oenorm_properties' => 'oenormProperties',
        'hierarchy_level' => 'hierarchyLevel',
        'addendum_status' => 'addendumStatus',
        'alternative_identifier' => 'alternativeIdentifier',
        'alternative_group_identifier' => 'alternativeGroupIdentifier'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'project_hourly_wage' => 'setProjectHourlyWage',
        'project_tax_rate' => 'setProjectTaxRate',
        'project_price_components' => 'setProjectPriceComponents',
        'project_item_number_schema' => 'setProjectItemNumberSchema',
        'elements' => 'setElements',
        'project_labour_time_label' => 'setProjectLabourTimeLabel',
        'contains_duplicate_item_numbers' => 'setContainsDuplicateItemNumbers',
        'contains_duplicate_element_ids' => 'setContainsDuplicateElementIds',
        'ignore_duplicate_item_numbers' => 'setIgnoreDuplicateItemNumbers',
        'ignore_project_catalogue_propagation' => 'setIgnoreProjectCataloguePropagation',
        'ignore_duplicate_element_ids' => 'setIgnoreDuplicateElementIds',
        'total_price_gross_by_tax_rate' => 'setTotalPriceGrossByTaxRate',
        'ignore_child_price_updates' => 'setIgnoreChildPriceUpdates',
        'deducted_price' => 'setDeductedPrice',
        'deduction_factor' => 'setDeductionFactor',
        'absolute_deduction' => 'setAbsoluteDeduction',
        'total_price' => 'setTotalPrice',
        'total_price_gross' => 'setTotalPriceGross',
        'total_price_gross_deducted' => 'setTotalPriceGrossDeducted',
        'price_type' => 'setPriceType',
        'short_text' => 'setShortText',
        'comission_status' => 'setComissionStatus',
        'item_number' => 'setItemNumber',
        'element_type' => 'setElementType',
        'is_lot' => 'setIsLot',
        'alternative_to' => 'setAlternativeTo',
        'oenorm_properties' => 'setOenormProperties',
        'hierarchy_level' => 'setHierarchyLevel',
        'addendum_status' => 'setAddendumStatus',
        'alternative_identifier' => 'setAlternativeIdentifier',
        'alternative_group_identifier' => 'setAlternativeGroupIdentifier'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'project_hourly_wage' => 'getProjectHourlyWage',
        'project_tax_rate' => 'getProjectTaxRate',
        'project_price_components' => 'getProjectPriceComponents',
        'project_item_number_schema' => 'getProjectItemNumberSchema',
        'elements' => 'getElements',
        'project_labour_time_label' => 'getProjectLabourTimeLabel',
        'contains_duplicate_item_numbers' => 'getContainsDuplicateItemNumbers',
        'contains_duplicate_element_ids' => 'getContainsDuplicateElementIds',
        'ignore_duplicate_item_numbers' => 'getIgnoreDuplicateItemNumbers',
        'ignore_project_catalogue_propagation' => 'getIgnoreProjectCataloguePropagation',
        'ignore_duplicate_element_ids' => 'getIgnoreDuplicateElementIds',
        'total_price_gross_by_tax_rate' => 'getTotalPriceGrossByTaxRate',
        'ignore_child_price_updates' => 'getIgnoreChildPriceUpdates',
        'deducted_price' => 'getDeductedPrice',
        'deduction_factor' => 'getDeductionFactor',
        'absolute_deduction' => 'getAbsoluteDeduction',
        'total_price' => 'getTotalPrice',
        'total_price_gross' => 'getTotalPriceGross',
        'total_price_gross_deducted' => 'getTotalPriceGrossDeducted',
        'price_type' => 'getPriceType',
        'short_text' => 'getShortText',
        'comission_status' => 'getComissionStatus',
        'item_number' => 'getItemNumber',
        'element_type' => 'getElementType',
        'is_lot' => 'getIsLot',
        'alternative_to' => 'getAlternativeTo',
        'oenorm_properties' => 'getOenormProperties',
        'hierarchy_level' => 'getHierarchyLevel',
        'addendum_status' => 'getAddendumStatus',
        'alternative_identifier' => 'getAlternativeIdentifier',
        'alternative_group_identifier' => 'getAlternativeGroupIdentifier'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }



    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        parent::__construct($data);

        $this->setIfExists('project_hourly_wage', $data ?? [], null);
        $this->setIfExists('project_tax_rate', $data ?? [], null);
        $this->setIfExists('project_price_components', $data ?? [], null);
        $this->setIfExists('project_item_number_schema', $data ?? [], null);
        $this->setIfExists('elements', $data ?? [], null);
        $this->setIfExists('project_labour_time_label', $data ?? [], null);
        $this->setIfExists('contains_duplicate_item_numbers', $data ?? [], null);
        $this->setIfExists('contains_duplicate_element_ids', $data ?? [], null);
        $this->setIfExists('ignore_duplicate_item_numbers', $data ?? [], null);
        $this->setIfExists('ignore_project_catalogue_propagation', $data ?? [], null);
        $this->setIfExists('ignore_duplicate_element_ids', $data ?? [], null);
        $this->setIfExists('total_price_gross_by_tax_rate', $data ?? [], null);
        $this->setIfExists('ignore_child_price_updates', $data ?? [], null);
        $this->setIfExists('deducted_price', $data ?? [], null);
        $this->setIfExists('deduction_factor', $data ?? [], null);
        $this->setIfExists('absolute_deduction', $data ?? [], null);
        $this->setIfExists('total_price', $data ?? [], null);
        $this->setIfExists('total_price_gross', $data ?? [], null);
        $this->setIfExists('total_price_gross_deducted', $data ?? [], null);
        $this->setIfExists('price_type', $data ?? [], null);
        $this->setIfExists('short_text', $data ?? [], null);
        $this->setIfExists('comission_status', $data ?? [], null);
        $this->setIfExists('item_number', $data ?? [], null);
        $this->setIfExists('element_type', $data ?? [], null);
        $this->setIfExists('is_lot', $data ?? [], null);
        $this->setIfExists('alternative_to', $data ?? [], null);
        $this->setIfExists('oenorm_properties', $data ?? [], null);
        $this->setIfExists('hierarchy_level', $data ?? [], null);
        $this->setIfExists('addendum_status', $data ?? [], null);
        $this->setIfExists('alternative_identifier', $data ?? [], null);
        $this->setIfExists('alternative_group_identifier', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        if ($this->container['project_hourly_wage'] === null) {
            $invalidProperties[] = "'project_hourly_wage' can't be null";
        }
        if ($this->container['project_tax_rate'] === null) {
            $invalidProperties[] = "'project_tax_rate' can't be null";
        }
        if ($this->container['contains_duplicate_item_numbers'] === null) {
            $invalidProperties[] = "'contains_duplicate_item_numbers' can't be null";
        }
        if ($this->container['contains_duplicate_element_ids'] === null) {
            $invalidProperties[] = "'contains_duplicate_element_ids' can't be null";
        }
        if ($this->container['ignore_duplicate_item_numbers'] === null) {
            $invalidProperties[] = "'ignore_duplicate_item_numbers' can't be null";
        }
        if ($this->container['ignore_project_catalogue_propagation'] === null) {
            $invalidProperties[] = "'ignore_project_catalogue_propagation' can't be null";
        }
        if ($this->container['ignore_duplicate_element_ids'] === null) {
            $invalidProperties[] = "'ignore_duplicate_element_ids' can't be null";
        }
        if ($this->container['ignore_child_price_updates'] === null) {
            $invalidProperties[] = "'ignore_child_price_updates' can't be null";
        }
        if ($this->container['deducted_price'] === null) {
            $invalidProperties[] = "'deducted_price' can't be null";
        }
        if ($this->container['deduction_factor'] === null) {
            $invalidProperties[] = "'deduction_factor' can't be null";
        }
        if ($this->container['total_price'] === null) {
            $invalidProperties[] = "'total_price' can't be null";
        }
        if ($this->container['total_price_gross'] === null) {
            $invalidProperties[] = "'total_price_gross' can't be null";
        }
        if ($this->container['total_price_gross_deducted'] === null) {
            $invalidProperties[] = "'total_price_gross_deducted' can't be null";
        }
        if ($this->container['price_type'] === null) {
            $invalidProperties[] = "'price_type' can't be null";
        }
        if ($this->container['comission_status'] === null) {
            $invalidProperties[] = "'comission_status' can't be null";
        }
        if ($this->container['is_lot'] === null) {
            $invalidProperties[] = "'is_lot' can't be null";
        }
        if ($this->container['hierarchy_level'] === null) {
            $invalidProperties[] = "'hierarchy_level' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets project_hourly_wage
     *
     * @return float
     */
    public function getProjectHourlyWage()
    {
        return $this->container['project_hourly_wage'];
    }

    /**
     * Sets project_hourly_wage
     *
     * @param float $project_hourly_wage The hourly wage that is used within this ElementContainerBase. Will be propagated to child elements.
     *
     * @return self
     */
    public function setProjectHourlyWage($project_hourly_wage)
    {
        if (is_null($project_hourly_wage)) {
            throw new \InvalidArgumentException('non-nullable project_hourly_wage cannot be null');
        }
        $this->container['project_hourly_wage'] = $project_hourly_wage;

        return $this;
    }

    /**
     * Gets project_tax_rate
     *
     * @return float
     */
    public function getProjectTaxRate()
    {
        return $this->container['project_tax_rate'];
    }

    /**
     * Sets project_tax_rate
     *
     * @param float $project_tax_rate The tax rate that is used within this ElementContainerBase. Will be propagated to child elements.
     *
     * @return self
     */
    public function setProjectTaxRate($project_tax_rate)
    {
        if (is_null($project_tax_rate)) {
            throw new \InvalidArgumentException('non-nullable project_tax_rate cannot be null');
        }
        $this->container['project_tax_rate'] = $project_tax_rate;

        return $this;
    }

    /**
     * Gets project_price_components
     *
     * @return string[]|null
     */
    public function getProjectPriceComponents()
    {
        return $this->container['project_price_components'];
    }

    /**
     * Sets project_price_components
     *
     * @param string[]|null $project_price_components The price components that are used within this project. They are ignored during Json deserialization because they will be set from the parent project.
     *
     * @return self
     */
    public function setProjectPriceComponents($project_price_components)
    {
        if (is_null($project_price_components)) {
            throw new \InvalidArgumentException('non-nullable project_price_components cannot be null');
        }
        $this->container['project_price_components'] = $project_price_components;

        return $this;
    }

    /**
     * Gets project_item_number_schema
     *
     * @return \Dangl\AVACloud\Model\ItemNumberSchemaDto|null
     */
    public function getProjectItemNumberSchema()
    {
        return $this->container['project_item_number_schema'];
    }

    /**
     * Sets project_item_number_schema
     *
     * @param \Dangl\AVACloud\Model\ItemNumberSchemaDto|null $project_item_number_schema project_item_number_schema
     *
     * @return self
     */
    public function setProjectItemNumberSchema($project_item_number_schema)
    {
        if (is_null($project_item_number_schema)) {
            throw new \InvalidArgumentException('non-nullable project_item_number_schema cannot be null');
        }
        $this->container['project_item_number_schema'] = $project_item_number_schema;

        return $this;
    }

    /**
     * Gets elements
     *
     * @return \Dangl\AVACloud\Model\IElementDto[]|null
     */
    public function getElements()
    {
        return $this->container['elements'];
    }

    /**
     * Sets elements
     *
     * @param \Dangl\AVACloud\Model\IElementDto[]|null $elements The IElements within this ElementContainerBase.
     *
     * @return self
     */
    public function setElements($elements)
    {
        if (is_null($elements)) {
            throw new \InvalidArgumentException('non-nullable elements cannot be null');
        }
        $this->container['elements'] = $elements;

        return $this;
    }

    /**
     * Gets project_labour_time_label
     *
     * @return string|null
     */
    public function getProjectLabourTimeLabel()
    {
        return $this->container['project_labour_time_label'];
    }

    /**
     * Sets project_labour_time_label
     *
     * @param string|null $project_labour_time_label The label used in the parent Project to mark labour time, e.g. \"Hours\" or \"Stunden\".
     *
     * @return self
     */
    public function setProjectLabourTimeLabel($project_labour_time_label)
    {
        if (is_null($project_labour_time_label)) {
            throw new \InvalidArgumentException('non-nullable project_labour_time_label cannot be null');
        }
        $this->container['project_labour_time_label'] = $project_labour_time_label;

        return $this;
    }

    /**
     * Gets contains_duplicate_item_numbers
     *
     * @return bool
     */
    public function getContainsDuplicateItemNumbers()
    {
        return $this->container['contains_duplicate_item_numbers'];
    }

    /**
     * Sets contains_duplicate_item_numbers
     *
     * @param bool $contains_duplicate_item_numbers Indicates if there are child IElements that have conflicting, duplicated ItemNumbers or if any child ElementContainerBase elements themselves contain duplicate ItemNumber s. Will always indicate false when told to ignore duplicate item numbers.
     *
     * @return self
     */
    public function setContainsDuplicateItemNumbers($contains_duplicate_item_numbers)
    {
        if (is_null($contains_duplicate_item_numbers)) {
            throw new \InvalidArgumentException('non-nullable contains_duplicate_item_numbers cannot be null');
        }
        $this->container['contains_duplicate_item_numbers'] = $contains_duplicate_item_numbers;

        return $this;
    }

    /**
     * Gets contains_duplicate_element_ids
     *
     * @return bool
     */
    public function getContainsDuplicateElementIds()
    {
        return $this->container['contains_duplicate_element_ids'];
    }

    /**
     * Sets contains_duplicate_element_ids
     *
     * @param bool $contains_duplicate_element_ids Indicates if there are child IElements that have conflicting, duplicated Ids or if any child ElementContainerBase elements themselves contain duplicate Id s. Will always indicate false when told to ignore duplicate item numbers.
     *
     * @return self
     */
    public function setContainsDuplicateElementIds($contains_duplicate_element_ids)
    {
        if (is_null($contains_duplicate_element_ids)) {
            throw new \InvalidArgumentException('non-nullable contains_duplicate_element_ids cannot be null');
        }
        $this->container['contains_duplicate_element_ids'] = $contains_duplicate_element_ids;

        return $this;
    }

    /**
     * Gets ignore_duplicate_item_numbers
     *
     * @return bool
     */
    public function getIgnoreDuplicateItemNumbers()
    {
        return $this->container['ignore_duplicate_item_numbers'];
    }

    /**
     * Sets ignore_duplicate_item_numbers
     *
     * @param bool $ignore_duplicate_item_numbers Indicate if duplicated ItemNumbers within child elements are to be ignored. Will not perform checks for duplicates if yes.
     *
     * @return self
     */
    public function setIgnoreDuplicateItemNumbers($ignore_duplicate_item_numbers)
    {
        if (is_null($ignore_duplicate_item_numbers)) {
            throw new \InvalidArgumentException('non-nullable ignore_duplicate_item_numbers cannot be null');
        }
        $this->container['ignore_duplicate_item_numbers'] = $ignore_duplicate_item_numbers;

        return $this;
    }

    /**
     * Gets ignore_project_catalogue_propagation
     *
     * @return bool
     */
    public function getIgnoreProjectCataloguePropagation()
    {
        return $this->container['ignore_project_catalogue_propagation'];
    }

    /**
     * Sets ignore_project_catalogue_propagation
     *
     * @param bool $ignore_project_catalogue_propagation If this is set to true, the ProjectCatalogues property will not be propagated to child elements. This is useful in mapping scenarios, where you want to disable propagation for multiple changes, and only enable it once you have mapped all properties
     *
     * @return self
     */
    public function setIgnoreProjectCataloguePropagation($ignore_project_catalogue_propagation)
    {
        if (is_null($ignore_project_catalogue_propagation)) {
            throw new \InvalidArgumentException('non-nullable ignore_project_catalogue_propagation cannot be null');
        }
        $this->container['ignore_project_catalogue_propagation'] = $ignore_project_catalogue_propagation;

        return $this;
    }

    /**
     * Gets ignore_duplicate_element_ids
     *
     * @return bool
     */
    public function getIgnoreDuplicateElementIds()
    {
        return $this->container['ignore_duplicate_element_ids'];
    }

    /**
     * Sets ignore_duplicate_element_ids
     *
     * @param bool $ignore_duplicate_element_ids Indicate if duplicated Ids within child elements are to be ignored. Will not perform checks for duplicates if yes.
     *
     * @return self
     */
    public function setIgnoreDuplicateElementIds($ignore_duplicate_element_ids)
    {
        if (is_null($ignore_duplicate_element_ids)) {
            throw new \InvalidArgumentException('non-nullable ignore_duplicate_element_ids cannot be null');
        }
        $this->container['ignore_duplicate_element_ids'] = $ignore_duplicate_element_ids;

        return $this;
    }

    /**
     * Gets total_price_gross_by_tax_rate
     *
     * @return \Dangl\AVACloud\Model\GrossPriceComponentDto[]|null
     */
    public function getTotalPriceGrossByTaxRate()
    {
        return $this->container['total_price_gross_by_tax_rate'];
    }

    /**
     * Sets total_price_gross_by_tax_rate
     *
     * @param \Dangl\AVACloud\Model\GrossPriceComponentDto[]|null $total_price_gross_by_tax_rate Price composition by tax rate.
     *
     * @return self
     */
    public function setTotalPriceGrossByTaxRate($total_price_gross_by_tax_rate)
    {
        if (is_null($total_price_gross_by_tax_rate)) {
            throw new \InvalidArgumentException('non-nullable total_price_gross_by_tax_rate cannot be null');
        }
        $this->container['total_price_gross_by_tax_rate'] = $total_price_gross_by_tax_rate;

        return $this;
    }

    /**
     * Gets ignore_child_price_updates
     *
     * @return bool
     */
    public function getIgnoreChildPriceUpdates()
    {
        return $this->container['ignore_child_price_updates'];
    }

    /**
     * Sets ignore_child_price_updates
     *
     * @param bool $ignore_child_price_updates Internally used to indicate that a propagation is currently done, this is done to not recalculate every single result from a lot of changes when it is sufficient to calculate the total price at once.
     *
     * @return self
     */
    public function setIgnoreChildPriceUpdates($ignore_child_price_updates)
    {
        if (is_null($ignore_child_price_updates)) {
            throw new \InvalidArgumentException('non-nullable ignore_child_price_updates cannot be null');
        }
        $this->container['ignore_child_price_updates'] = $ignore_child_price_updates;

        return $this;
    }

    /**
     * Gets deducted_price
     *
     * @return float
     */
    public function getDeductedPrice()
    {
        return $this->container['deducted_price'];
    }

    /**
     * Sets deducted_price
     *
     * @param float $deducted_price Net price after applied deductions.
     *
     * @return self
     */
    public function setDeductedPrice($deducted_price)
    {
        if (is_null($deducted_price)) {
            throw new \InvalidArgumentException('non-nullable deducted_price cannot be null');
        }
        $this->container['deducted_price'] = $deducted_price;

        return $this;
    }

    /**
     * Gets deduction_factor
     *
     * @return float
     */
    public function getDeductionFactor()
    {
        return $this->container['deduction_factor'];
    }

    /**
     * Sets deduction_factor
     *
     * @param float $deduction_factor Factor of applied deductions to the total price. For example, \"0.03\" means that a 3% deduction is to be applied.
     *
     * @return self
     */
    public function setDeductionFactor($deduction_factor)
    {
        if (is_null($deduction_factor)) {
            throw new \InvalidArgumentException('non-nullable deduction_factor cannot be null');
        }
        $this->container['deduction_factor'] = $deduction_factor;

        return $this;
    }

    /**
     * Gets absolute_deduction
     *
     * @return float|null
     */
    public function getAbsoluteDeduction()
    {
        return $this->container['absolute_deduction'];
    }

    /**
     * Sets absolute_deduction
     *
     * @param float|null $absolute_deduction The exact amount of the discount as an absolute value. For backwards compatibility reasons, setting this value will also set a calculated value to DeductionFactor, which will also be updated in case the total price is changed to reflect a relative value of the absolute discount sum.
     *
     * @return self
     */
    public function setAbsoluteDeduction($absolute_deduction)
    {
        if (is_null($absolute_deduction)) {
            throw new \InvalidArgumentException('non-nullable absolute_deduction cannot be null');
        }
        $this->container['absolute_deduction'] = $absolute_deduction;

        return $this;
    }

    /**
     * Gets total_price
     *
     * @return float
     */
    public function getTotalPrice()
    {
        return $this->container['total_price'];
    }

    /**
     * Sets total_price
     *
     * @param float $total_price Will return this ElementContainerBase's total price.
     *
     * @return self
     */
    public function setTotalPrice($total_price)
    {
        if (is_null($total_price)) {
            throw new \InvalidArgumentException('non-nullable total_price cannot be null');
        }
        $this->container['total_price'] = $total_price;

        return $this;
    }

    /**
     * Gets total_price_gross
     *
     * @return float
     */
    public function getTotalPriceGross()
    {
        return $this->container['total_price_gross'];
    }

    /**
     * Sets total_price_gross
     *
     * @param float $total_price_gross The total gross price for this ElementContainerBase including all child elements.
     *
     * @return self
     */
    public function setTotalPriceGross($total_price_gross)
    {
        if (is_null($total_price_gross)) {
            throw new \InvalidArgumentException('non-nullable total_price_gross cannot be null');
        }
        $this->container['total_price_gross'] = $total_price_gross;

        return $this;
    }

    /**
     * Gets total_price_gross_deducted
     *
     * @return float
     */
    public function getTotalPriceGrossDeducted()
    {
        return $this->container['total_price_gross_deducted'];
    }

    /**
     * Sets total_price_gross_deducted
     *
     * @param float $total_price_gross_deducted Total gross price after applied deductions.
     *
     * @return self
     */
    public function setTotalPriceGrossDeducted($total_price_gross_deducted)
    {
        if (is_null($total_price_gross_deducted)) {
            throw new \InvalidArgumentException('non-nullable total_price_gross_deducted cannot be null');
        }
        $this->container['total_price_gross_deducted'] = $total_price_gross_deducted;

        return $this;
    }

    /**
     * Gets price_type
     *
     * @return \Dangl\AVACloud\Model\PriceTypeDto
     */
    public function getPriceType()
    {
        return $this->container['price_type'];
    }

    /**
     * Sets price_type
     *
     * @param \Dangl\AVACloud\Model\PriceTypeDto $price_type price_type
     *
     * @return self
     */
    public function setPriceType($price_type)
    {
        if (is_null($price_type)) {
            throw new \InvalidArgumentException('non-nullable price_type cannot be null');
        }
        $this->container['price_type'] = $price_type;

        return $this;
    }

    /**
     * Gets short_text
     *
     * @return string|null
     */
    public function getShortText()
    {
        return $this->container['short_text'];
    }

    /**
     * Sets short_text
     *
     * @param string|null $short_text Description for this ServiceSpecificationGroup.
     *
     * @return self
     */
    public function setShortText($short_text)
    {
        if (is_null($short_text)) {
            throw new \InvalidArgumentException('non-nullable short_text cannot be null');
        }
        $this->container['short_text'] = $short_text;

        return $this;
    }

    /**
     * Gets comission_status
     *
     * @return \Dangl\AVACloud\Model\ComissionStatusDto
     */
    public function getComissionStatus()
    {
        return $this->container['comission_status'];
    }

    /**
     * Sets comission_status
     *
     * @param \Dangl\AVACloud\Model\ComissionStatusDto $comission_status comission_status
     *
     * @return self
     */
    public function setComissionStatus($comission_status)
    {
        if (is_null($comission_status)) {
            throw new \InvalidArgumentException('non-nullable comission_status cannot be null');
        }
        $this->container['comission_status'] = $comission_status;

        return $this;
    }

    /**
     * Gets item_number
     *
     * @return \Dangl\AVACloud\Model\ItemNumberDto|null
     */
    public function getItemNumber()
    {
        return $this->container['item_number'];
    }

    /**
     * Sets item_number
     *
     * @param \Dangl\AVACloud\Model\ItemNumberDto|null $item_number item_number
     *
     * @return self
     */
    public function setItemNumber($item_number)
    {
        if (is_null($item_number)) {
            throw new \InvalidArgumentException('non-nullable item_number cannot be null');
        }
        $this->container['item_number'] = $item_number;

        return $this;
    }

    /**
     * Gets element_type
     *
     * @return string|null
     */
    public function getElementType()
    {
        return $this->container['element_type'];
    }

    /**
     * Sets element_type
     *
     * @param string|null $element_type element_type
     *
     * @return self
     */
    public function setElementType($element_type)
    {
        if (is_null($element_type)) {
            throw new \InvalidArgumentException('non-nullable element_type cannot be null');
        }
        $this->container['element_type'] = $element_type;

        return $this;
    }

    /**
     * Gets is_lot
     *
     * @return bool
     */
    public function getIsLot()
    {
        return $this->container['is_lot'];
    }

    /**
     * Sets is_lot
     *
     * @param bool $is_lot This indicates if this group is the parent of a lot. See the documentation for more information about working with lots.
     *
     * @return self
     */
    public function setIsLot($is_lot)
    {
        if (is_null($is_lot)) {
            throw new \InvalidArgumentException('non-nullable is_lot cannot be null');
        }
        $this->container['is_lot'] = $is_lot;

        return $this;
    }

    /**
     * Gets alternative_to
     *
     * @return string|null
     */
    public function getAlternativeTo()
    {
        return $this->container['alternative_to'];
    }

    /**
     * Sets alternative_to
     *
     * @param string|null $alternative_to If this group is an alternative for a base group, then this property should point to the id of the group in this service specification that it can replace. If this is an alternative group to a base group, the PriceType should typically be set to \"WithoutTotal\" so this group does not factor into total costs. The PriceType is not changed when this property is set
     *
     * @return self
     */
    public function setAlternativeTo($alternative_to)
    {
        if (is_null($alternative_to)) {
            throw new \InvalidArgumentException('non-nullable alternative_to cannot be null');
        }
        $this->container['alternative_to'] = $alternative_to;

        return $this;
    }

    /**
     * Gets oenorm_properties
     *
     * @return \Dangl\AVACloud\Model\OenormPropertiesDto|null
     */
    public function getOenormProperties()
    {
        return $this->container['oenorm_properties'];
    }

    /**
     * Sets oenorm_properties
     *
     * @param \Dangl\AVACloud\Model\OenormPropertiesDto|null $oenorm_properties oenorm_properties
     *
     * @return self
     */
    public function setOenormProperties($oenorm_properties)
    {
        if (is_null($oenorm_properties)) {
            throw new \InvalidArgumentException('non-nullable oenorm_properties cannot be null');
        }
        $this->container['oenorm_properties'] = $oenorm_properties;

        return $this;
    }

    /**
     * Gets hierarchy_level
     *
     * @return int
     */
    public function getHierarchyLevel()
    {
        return $this->container['hierarchy_level'];
    }

    /**
     * Sets hierarchy_level
     *
     * @param int $hierarchy_level This is a zero based hierarchy level. It's set automatically when used in the context of a Project, and can be used to identify the hierarchy level of the current element.
     *
     * @return self
     */
    public function setHierarchyLevel($hierarchy_level)
    {
        if (is_null($hierarchy_level)) {
            throw new \InvalidArgumentException('non-nullable hierarchy_level cannot be null');
        }
        $this->container['hierarchy_level'] = $hierarchy_level;

        return $this;
    }

    /**
     * Gets addendum_status
     *
     * @return \Dangl\AVACloud\Model\AddendumStatusDto|null
     */
    public function getAddendumStatus()
    {
        return $this->container['addendum_status'];
    }

    /**
     * Sets addendum_status
     *
     * @param \Dangl\AVACloud\Model\AddendumStatusDto|null $addendum_status addendum_status
     *
     * @return self
     */
    public function setAddendumStatus($addendum_status)
    {
        if (is_null($addendum_status)) {
            throw new \InvalidArgumentException('non-nullable addendum_status cannot be null');
        }
        $this->container['addendum_status'] = $addendum_status;

        return $this;
    }

    /**
     * Gets alternative_identifier
     *
     * @return int|null
     */
    public function getAlternativeIdentifier()
    {
        return $this->container['alternative_identifier'];
    }

    /**
     * Sets alternative_identifier
     *
     * @param int|null $alternative_identifier This is an optional property that can be used together with AlternativeTo. If this is set, you can indicate which alternative group a specific group is assigned to. That way, if you specifiy multiple alternative ServiceSpecificationGroups with the same AlternativeIdentifier, you can indicate that to replace a single base ServiceSpecificationGroup, multiple alternative ServiceSpecificationGroups should be used. This property is not checked or managed automatically, so it is possible for this property to become invalid, by for example setting this property but not setting a base group via AlternativeTo.
     *
     * @return self
     */
    public function setAlternativeIdentifier($alternative_identifier)
    {
        if (is_null($alternative_identifier)) {
            throw new \InvalidArgumentException('non-nullable alternative_identifier cannot be null');
        }
        $this->container['alternative_identifier'] = $alternative_identifier;

        return $this;
    }

    /**
     * Gets alternative_group_identifier
     *
     * @return int|null
     */
    public function getAlternativeGroupIdentifier()
    {
        return $this->container['alternative_group_identifier'];
    }

    /**
     * Sets alternative_group_identifier
     *
     * @param int|null $alternative_group_identifier This is an optional property that can be used together with AlternativeTo and AlternativeGroupIdentifier. If this is set, you can indicate which alternative group a specific group is assigned to. That way, you can specify the id (in integer format) for the alternative group this group belongs to. It's different to AlternativeIdentifier in that the other property describes the id of the group, while this property here describes the group itself. If a group only has set AlternativeGroupIdentifier but not AlternativeIdentifier, then it likely is a base group for a specific group. This property is not checked or managed automatically, so it is possible for this property to become invalid, by for example setting this property but not setting a base group via AlternativeTo.
     *
     * @return self
     */
    public function setAlternativeGroupIdentifier($alternative_group_identifier)
    {
        if (is_null($alternative_group_identifier)) {
            throw new \InvalidArgumentException('non-nullable alternative_group_identifier cannot be null');
        }
        $this->container['alternative_group_identifier'] = $alternative_group_identifier;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


