<?php
/**
 * ServiceSpecificationCommercePropertiesDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dangl\AVACloud\Model;

use \ArrayAccess;
use \Dangl\AVACloud\ObjectSerializer;

/**
 * ServiceSpecificationCommercePropertiesDto Class Doc Comment
 *
 * @category Class
 * @description This class represents properties used in commerce exchange scenarios
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ServiceSpecificationCommercePropertiesDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ServiceSpecificationCommercePropertiesDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'fixed_price_date' => '\DateTime',
        'delivery_voucher_date' => '\DateTime',
        'delivery_date' => '\DateTime',
        'inquiry_number' => 'string',
        'offer_number' => 'string',
        'order_number' => 'string',
        'order_confirmation_number' => 'string',
        'delivery_number' => 'string',
        'customer_reference_number' => 'string',
        'supplier_reference_number' => 'string',
        'shipping_type' => 'string',
        'inquiry_type' => '\Dangl\AVACloud\Model\CommerceInquiryTypeDto'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'fixed_price_date' => 'date-time',
        'delivery_voucher_date' => 'date-time',
        'delivery_date' => 'date-time',
        'inquiry_number' => null,
        'offer_number' => null,
        'order_number' => null,
        'order_confirmation_number' => null,
        'delivery_number' => null,
        'customer_reference_number' => null,
        'supplier_reference_number' => null,
        'shipping_type' => null,
        'inquiry_type' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'fixed_price_date' => false,
        'delivery_voucher_date' => false,
        'delivery_date' => false,
        'inquiry_number' => false,
        'offer_number' => false,
        'order_number' => false,
        'order_confirmation_number' => false,
        'delivery_number' => false,
        'customer_reference_number' => false,
        'supplier_reference_number' => false,
        'shipping_type' => false,
        'inquiry_type' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fixed_price_date' => 'fixedPriceDate',
        'delivery_voucher_date' => 'deliveryVoucherDate',
        'delivery_date' => 'deliveryDate',
        'inquiry_number' => 'inquiryNumber',
        'offer_number' => 'offerNumber',
        'order_number' => 'orderNumber',
        'order_confirmation_number' => 'orderConfirmationNumber',
        'delivery_number' => 'deliveryNumber',
        'customer_reference_number' => 'customerReferenceNumber',
        'supplier_reference_number' => 'supplierReferenceNumber',
        'shipping_type' => 'shippingType',
        'inquiry_type' => 'inquiryType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fixed_price_date' => 'setFixedPriceDate',
        'delivery_voucher_date' => 'setDeliveryVoucherDate',
        'delivery_date' => 'setDeliveryDate',
        'inquiry_number' => 'setInquiryNumber',
        'offer_number' => 'setOfferNumber',
        'order_number' => 'setOrderNumber',
        'order_confirmation_number' => 'setOrderConfirmationNumber',
        'delivery_number' => 'setDeliveryNumber',
        'customer_reference_number' => 'setCustomerReferenceNumber',
        'supplier_reference_number' => 'setSupplierReferenceNumber',
        'shipping_type' => 'setShippingType',
        'inquiry_type' => 'setInquiryType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fixed_price_date' => 'getFixedPriceDate',
        'delivery_voucher_date' => 'getDeliveryVoucherDate',
        'delivery_date' => 'getDeliveryDate',
        'inquiry_number' => 'getInquiryNumber',
        'offer_number' => 'getOfferNumber',
        'order_number' => 'getOrderNumber',
        'order_confirmation_number' => 'getOrderConfirmationNumber',
        'delivery_number' => 'getDeliveryNumber',
        'customer_reference_number' => 'getCustomerReferenceNumber',
        'supplier_reference_number' => 'getSupplierReferenceNumber',
        'shipping_type' => 'getShippingType',
        'inquiry_type' => 'getInquiryType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('fixed_price_date', $data ?? [], null);
        $this->setIfExists('delivery_voucher_date', $data ?? [], null);
        $this->setIfExists('delivery_date', $data ?? [], null);
        $this->setIfExists('inquiry_number', $data ?? [], null);
        $this->setIfExists('offer_number', $data ?? [], null);
        $this->setIfExists('order_number', $data ?? [], null);
        $this->setIfExists('order_confirmation_number', $data ?? [], null);
        $this->setIfExists('delivery_number', $data ?? [], null);
        $this->setIfExists('customer_reference_number', $data ?? [], null);
        $this->setIfExists('supplier_reference_number', $data ?? [], null);
        $this->setIfExists('shipping_type', $data ?? [], null);
        $this->setIfExists('inquiry_type', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['inquiry_type'] === null) {
            $invalidProperties[] = "'inquiry_type' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fixed_price_date
     *
     * @return \DateTime|null
     */
    public function getFixedPriceDate()
    {
        return $this->container['fixed_price_date'];
    }

    /**
     * Sets fixed_price_date
     *
     * @param \DateTime|null $fixed_price_date The date until the price is valid or fixed.
     *
     * @return self
     */
    public function setFixedPriceDate($fixed_price_date)
    {
        if (is_null($fixed_price_date)) {
            throw new \InvalidArgumentException('non-nullable fixed_price_date cannot be null');
        }
        $this->container['fixed_price_date'] = $fixed_price_date;

        return $this;
    }

    /**
     * Gets delivery_voucher_date
     *
     * @return \DateTime|null
     */
    public function getDeliveryVoucherDate()
    {
        return $this->container['delivery_voucher_date'];
    }

    /**
     * Sets delivery_voucher_date
     *
     * @param \DateTime|null $delivery_voucher_date The date of the delivery voucher note.
     *
     * @return self
     */
    public function setDeliveryVoucherDate($delivery_voucher_date)
    {
        if (is_null($delivery_voucher_date)) {
            throw new \InvalidArgumentException('non-nullable delivery_voucher_date cannot be null');
        }
        $this->container['delivery_voucher_date'] = $delivery_voucher_date;

        return $this;
    }

    /**
     * Gets delivery_date
     *
     * @return \DateTime|null
     */
    public function getDeliveryDate()
    {
        return $this->container['delivery_date'];
    }

    /**
     * Sets delivery_date
     *
     * @param \DateTime|null $delivery_date The actual date of delivery.
     *
     * @return self
     */
    public function setDeliveryDate($delivery_date)
    {
        if (is_null($delivery_date)) {
            throw new \InvalidArgumentException('non-nullable delivery_date cannot be null');
        }
        $this->container['delivery_date'] = $delivery_date;

        return $this;
    }

    /**
     * Gets inquiry_number
     *
     * @return string|null
     */
    public function getInquiryNumber()
    {
        return $this->container['inquiry_number'];
    }

    /**
     * Sets inquiry_number
     *
     * @param string|null $inquiry_number The number of the inquiry, usually in a context of offer requests.
     *
     * @return self
     */
    public function setInquiryNumber($inquiry_number)
    {
        if (is_null($inquiry_number)) {
            throw new \InvalidArgumentException('non-nullable inquiry_number cannot be null');
        }
        $this->container['inquiry_number'] = $inquiry_number;

        return $this;
    }

    /**
     * Gets offer_number
     *
     * @return string|null
     */
    public function getOfferNumber()
    {
        return $this->container['offer_number'];
    }

    /**
     * Sets offer_number
     *
     * @param string|null $offer_number The number of the offer, usually in a context of an offer.
     *
     * @return self
     */
    public function setOfferNumber($offer_number)
    {
        if (is_null($offer_number)) {
            throw new \InvalidArgumentException('non-nullable offer_number cannot be null');
        }
        $this->container['offer_number'] = $offer_number;

        return $this;
    }

    /**
     * Gets order_number
     *
     * @return string|null
     */
    public function getOrderNumber()
    {
        return $this->container['order_number'];
    }

    /**
     * Sets order_number
     *
     * @param string|null $order_number The order number, usually in the context of a grant or contract.
     *
     * @return self
     */
    public function setOrderNumber($order_number)
    {
        if (is_null($order_number)) {
            throw new \InvalidArgumentException('non-nullable order_number cannot be null');
        }
        $this->container['order_number'] = $order_number;

        return $this;
    }

    /**
     * Gets order_confirmation_number
     *
     * @return string|null
     */
    public function getOrderConfirmationNumber()
    {
        return $this->container['order_confirmation_number'];
    }

    /**
     * Sets order_confirmation_number
     *
     * @param string|null $order_confirmation_number The order confirmation number
     *
     * @return self
     */
    public function setOrderConfirmationNumber($order_confirmation_number)
    {
        if (is_null($order_confirmation_number)) {
            throw new \InvalidArgumentException('non-nullable order_confirmation_number cannot be null');
        }
        $this->container['order_confirmation_number'] = $order_confirmation_number;

        return $this;
    }

    /**
     * Gets delivery_number
     *
     * @return string|null
     */
    public function getDeliveryNumber()
    {
        return $this->container['delivery_number'];
    }

    /**
     * Sets delivery_number
     *
     * @param string|null $delivery_number The number of the delivery, e.g. on the delivery note voucher.
     *
     * @return self
     */
    public function setDeliveryNumber($delivery_number)
    {
        if (is_null($delivery_number)) {
            throw new \InvalidArgumentException('non-nullable delivery_number cannot be null');
        }
        $this->container['delivery_number'] = $delivery_number;

        return $this;
    }

    /**
     * Gets customer_reference_number
     *
     * @return string|null
     */
    public function getCustomerReferenceNumber()
    {
        return $this->container['customer_reference_number'];
    }

    /**
     * Sets customer_reference_number
     *
     * @param string|null $customer_reference_number The reference number of the customer / buyer.
     *
     * @return self
     */
    public function setCustomerReferenceNumber($customer_reference_number)
    {
        if (is_null($customer_reference_number)) {
            throw new \InvalidArgumentException('non-nullable customer_reference_number cannot be null');
        }
        $this->container['customer_reference_number'] = $customer_reference_number;

        return $this;
    }

    /**
     * Gets supplier_reference_number
     *
     * @return string|null
     */
    public function getSupplierReferenceNumber()
    {
        return $this->container['supplier_reference_number'];
    }

    /**
     * Sets supplier_reference_number
     *
     * @param string|null $supplier_reference_number The reference number of the supplier / bidder.
     *
     * @return self
     */
    public function setSupplierReferenceNumber($supplier_reference_number)
    {
        if (is_null($supplier_reference_number)) {
            throw new \InvalidArgumentException('non-nullable supplier_reference_number cannot be null');
        }
        $this->container['supplier_reference_number'] = $supplier_reference_number;

        return $this;
    }

    /**
     * Gets shipping_type
     *
     * @return string|null
     */
    public function getShippingType()
    {
        return $this->container['shipping_type'];
    }

    /**
     * Sets shipping_type
     *
     * @param string|null $shipping_type The type of shippment.
     *
     * @return self
     */
    public function setShippingType($shipping_type)
    {
        if (is_null($shipping_type)) {
            throw new \InvalidArgumentException('non-nullable shipping_type cannot be null');
        }
        $this->container['shipping_type'] = $shipping_type;

        return $this;
    }

    /**
     * Gets inquiry_type
     *
     * @return \Dangl\AVACloud\Model\CommerceInquiryTypeDto
     */
    public function getInquiryType()
    {
        return $this->container['inquiry_type'];
    }

    /**
     * Sets inquiry_type
     *
     * @param \Dangl\AVACloud\Model\CommerceInquiryTypeDto $inquiry_type inquiry_type
     *
     * @return self
     */
    public function setInquiryType($inquiry_type)
    {
        if (is_null($inquiry_type)) {
            throw new \InvalidArgumentException('non-nullable inquiry_type cannot be null');
        }
        $this->container['inquiry_type'] = $inquiry_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


