<?php
/**
 * VatBreakdown
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dangl\AVACloud\Model;

use \ArrayAccess;
use \Dangl\AVACloud\ObjectSerializer;

/**
 * VatBreakdown Class Doc Comment
 *
 * @category Class
 * @description Describes the VAT breakdown for an invoice in a single VAT category
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class VatBreakdown implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'VatBreakdown';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'net_taxable_amount' => 'float',
        'vat_amount' => 'float',
        'vat_category' => '\Dangl\AVACloud\Model\VatCategory',
        'tax_rate' => 'float',
        'vat_exemption_reason_text' => 'string',
        'vat_exemption_reason_code' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'net_taxable_amount' => 'decimal',
        'vat_amount' => 'decimal',
        'vat_category' => null,
        'tax_rate' => 'decimal',
        'vat_exemption_reason_text' => null,
        'vat_exemption_reason_code' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'net_taxable_amount' => false,
        'vat_amount' => false,
        'vat_category' => false,
        'tax_rate' => false,
        'vat_exemption_reason_text' => false,
        'vat_exemption_reason_code' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'net_taxable_amount' => 'netTaxableAmount',
        'vat_amount' => 'vatAmount',
        'vat_category' => 'vatCategory',
        'tax_rate' => 'taxRate',
        'vat_exemption_reason_text' => 'vatExemptionReasonText',
        'vat_exemption_reason_code' => 'vatExemptionReasonCode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'net_taxable_amount' => 'setNetTaxableAmount',
        'vat_amount' => 'setVatAmount',
        'vat_category' => 'setVatCategory',
        'tax_rate' => 'setTaxRate',
        'vat_exemption_reason_text' => 'setVatExemptionReasonText',
        'vat_exemption_reason_code' => 'setVatExemptionReasonCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'net_taxable_amount' => 'getNetTaxableAmount',
        'vat_amount' => 'getVatAmount',
        'vat_category' => 'getVatCategory',
        'tax_rate' => 'getTaxRate',
        'vat_exemption_reason_text' => 'getVatExemptionReasonText',
        'vat_exemption_reason_code' => 'getVatExemptionReasonCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('net_taxable_amount', $data ?? [], null);
        $this->setIfExists('vat_amount', $data ?? [], null);
        $this->setIfExists('vat_category', $data ?? [], null);
        $this->setIfExists('tax_rate', $data ?? [], null);
        $this->setIfExists('vat_exemption_reason_text', $data ?? [], null);
        $this->setIfExists('vat_exemption_reason_code', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['vat_category'] === null) {
            $invalidProperties[] = "'vat_category' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets net_taxable_amount
     *
     * @return float|null
     */
    public function getNetTaxableAmount()
    {
        return $this->container['net_taxable_amount'];
    }

    /**
     * Sets net_taxable_amount
     *
     * @param float|null $net_taxable_amount BT-116 The total net amount of this VAT category
     *
     * @return self
     */
    public function setNetTaxableAmount($net_taxable_amount)
    {
        if (is_null($net_taxable_amount)) {
            throw new \InvalidArgumentException('non-nullable net_taxable_amount cannot be null');
        }
        $this->container['net_taxable_amount'] = $net_taxable_amount;

        return $this;
    }

    /**
     * Gets vat_amount
     *
     * @return float|null
     */
    public function getVatAmount()
    {
        return $this->container['vat_amount'];
    }

    /**
     * Sets vat_amount
     *
     * @param float|null $vat_amount BT-117 The total VAT
     *
     * @return self
     */
    public function setVatAmount($vat_amount)
    {
        if (is_null($vat_amount)) {
            throw new \InvalidArgumentException('non-nullable vat_amount cannot be null');
        }
        $this->container['vat_amount'] = $vat_amount;

        return $this;
    }

    /**
     * Gets vat_category
     *
     * @return \Dangl\AVACloud\Model\VatCategory
     */
    public function getVatCategory()
    {
        return $this->container['vat_category'];
    }

    /**
     * Sets vat_category
     *
     * @param \Dangl\AVACloud\Model\VatCategory $vat_category vat_category
     *
     * @return self
     */
    public function setVatCategory($vat_category)
    {
        if (is_null($vat_category)) {
            throw new \InvalidArgumentException('non-nullable vat_category cannot be null');
        }
        $this->container['vat_category'] = $vat_category;

        return $this;
    }

    /**
     * Gets tax_rate
     *
     * @return float|null
     */
    public function getTaxRate()
    {
        return $this->container['tax_rate'];
    }

    /**
     * Sets tax_rate
     *
     * @param float|null $tax_rate BT-119 The actual tax rate as a decimal value, e.g. 19% would be 0.19
     *
     * @return self
     */
    public function setTaxRate($tax_rate)
    {
        if (is_null($tax_rate)) {
            throw new \InvalidArgumentException('non-nullable tax_rate cannot be null');
        }
        $this->container['tax_rate'] = $tax_rate;

        return $this;
    }

    /**
     * Gets vat_exemption_reason_text
     *
     * @return string|null
     */
    public function getVatExemptionReasonText()
    {
        return $this->container['vat_exemption_reason_text'];
    }

    /**
     * Sets vat_exemption_reason_text
     *
     * @param string|null $vat_exemption_reason_text BT-120 If the VAT is exempt, there should be a description here. For example, in reverse charge scenarios, this text should contain a reference to \"Reverse charge according to ...\".
     *
     * @return self
     */
    public function setVatExemptionReasonText($vat_exemption_reason_text)
    {
        if (is_null($vat_exemption_reason_text)) {
            throw new \InvalidArgumentException('non-nullable vat_exemption_reason_text cannot be null');
        }
        $this->container['vat_exemption_reason_text'] = $vat_exemption_reason_text;

        return $this;
    }

    /**
     * Gets vat_exemption_reason_code
     *
     * @return string|null
     */
    public function getVatExemptionReasonCode()
    {
        return $this->container['vat_exemption_reason_code'];
    }

    /**
     * Sets vat_exemption_reason_code
     *
     * @param string|null $vat_exemption_reason_code BT-121 A code from the VAT exemption reason code list(VATEX)“
     *
     * @return self
     */
    public function setVatExemptionReasonCode($vat_exemption_reason_code)
    {
        if (is_null($vat_exemption_reason_code)) {
            throw new \InvalidArgumentException('non-nullable vat_exemption_reason_code cannot be null');
        }
        $this->container['vat_exemption_reason_code'] = $vat_exemption_reason_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


