<?php
/**
 * VatBreakdown
 *
 * PHP version 5
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AVACloud API 1.64.0
 *
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.64.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.50
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Dangl\AVACloud\Model;

use \ArrayAccess;
use \Dangl\AVACloud\ObjectSerializer;

/**
 * VatBreakdown Class Doc Comment
 *
 * @category Class
 * @description Describes the VAT breakdown for an invoice in a single VAT category
 * @package  Dangl\AVACloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VatBreakdown implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'VatBreakdown';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'net_taxable_amount' => 'float',
        'vat_amount' => 'float',
        'vat_category' => '\Dangl\AVACloud\Model\VatCategory',
        'tax_rate' => 'float',
        'vat_exemption_reason_text' => 'string',
        'vat_exemption_reason_code' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'net_taxable_amount' => 'decimal',
        'vat_amount' => 'decimal',
        'vat_category' => null,
        'tax_rate' => 'decimal',
        'vat_exemption_reason_text' => null,
        'vat_exemption_reason_code' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'net_taxable_amount' => 'netTaxableAmount',
        'vat_amount' => 'vatAmount',
        'vat_category' => 'vatCategory',
        'tax_rate' => 'taxRate',
        'vat_exemption_reason_text' => 'vatExemptionReasonText',
        'vat_exemption_reason_code' => 'vatExemptionReasonCode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'net_taxable_amount' => 'setNetTaxableAmount',
        'vat_amount' => 'setVatAmount',
        'vat_category' => 'setVatCategory',
        'tax_rate' => 'setTaxRate',
        'vat_exemption_reason_text' => 'setVatExemptionReasonText',
        'vat_exemption_reason_code' => 'setVatExemptionReasonCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'net_taxable_amount' => 'getNetTaxableAmount',
        'vat_amount' => 'getVatAmount',
        'vat_category' => 'getVatCategory',
        'tax_rate' => 'getTaxRate',
        'vat_exemption_reason_text' => 'getVatExemptionReasonText',
        'vat_exemption_reason_code' => 'getVatExemptionReasonCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['net_taxable_amount'] = isset($data['net_taxable_amount']) ? $data['net_taxable_amount'] : null;
        $this->container['vat_amount'] = isset($data['vat_amount']) ? $data['vat_amount'] : null;
        $this->container['vat_category'] = isset($data['vat_category']) ? $data['vat_category'] : null;
        $this->container['tax_rate'] = isset($data['tax_rate']) ? $data['tax_rate'] : null;
        $this->container['vat_exemption_reason_text'] = isset($data['vat_exemption_reason_text']) ? $data['vat_exemption_reason_text'] : null;
        $this->container['vat_exemption_reason_code'] = isset($data['vat_exemption_reason_code']) ? $data['vat_exemption_reason_code'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['vat_category'] === null) {
            $invalidProperties[] = "'vat_category' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets net_taxable_amount
     *
     * @return float
     */
    public function getNetTaxableAmount()
    {
        return $this->container['net_taxable_amount'];
    }

    /**
     * Sets net_taxable_amount
     *
     * @param float $net_taxable_amount BT-116 The total net amount of this VAT category
     *
     * @return $this
     */
    public function setNetTaxableAmount($net_taxable_amount)
    {
        $this->container['net_taxable_amount'] = $net_taxable_amount;

        return $this;
    }

    /**
     * Gets vat_amount
     *
     * @return float
     */
    public function getVatAmount()
    {
        return $this->container['vat_amount'];
    }

    /**
     * Sets vat_amount
     *
     * @param float $vat_amount BT-117 The total VAT
     *
     * @return $this
     */
    public function setVatAmount($vat_amount)
    {
        $this->container['vat_amount'] = $vat_amount;

        return $this;
    }

    /**
     * Gets vat_category
     *
     * @return \Dangl\AVACloud\Model\VatCategory
     */
    public function getVatCategory()
    {
        return $this->container['vat_category'];
    }

    /**
     * Sets vat_category
     *
     * @param \Dangl\AVACloud\Model\VatCategory $vat_category BT-118 The category of the VAT
     *
     * @return $this
     */
    public function setVatCategory($vat_category)
    {
        $this->container['vat_category'] = $vat_category;

        return $this;
    }

    /**
     * Gets tax_rate
     *
     * @return float
     */
    public function getTaxRate()
    {
        return $this->container['tax_rate'];
    }

    /**
     * Sets tax_rate
     *
     * @param float $tax_rate BT-119 The actual tax rate as a decimal value, e.g. 19% would be 0.19
     *
     * @return $this
     */
    public function setTaxRate($tax_rate)
    {
        $this->container['tax_rate'] = $tax_rate;

        return $this;
    }

    /**
     * Gets vat_exemption_reason_text
     *
     * @return string
     */
    public function getVatExemptionReasonText()
    {
        return $this->container['vat_exemption_reason_text'];
    }

    /**
     * Sets vat_exemption_reason_text
     *
     * @param string $vat_exemption_reason_text BT-120 If the VAT is exempt, there should be a description here. For example, in reverse charge scenarios, this text should contain a reference to \"Reverse charge according to ...\".
     *
     * @return $this
     */
    public function setVatExemptionReasonText($vat_exemption_reason_text)
    {
        $this->container['vat_exemption_reason_text'] = $vat_exemption_reason_text;

        return $this;
    }

    /**
     * Gets vat_exemption_reason_code
     *
     * @return string
     */
    public function getVatExemptionReasonCode()
    {
        return $this->container['vat_exemption_reason_code'];
    }

    /**
     * Sets vat_exemption_reason_code
     *
     * @param string $vat_exemption_reason_code BT-121 A code from the VAT exemption reason code list(VATEX)“
     *
     * @return $this
     */
    public function setVatExemptionReasonCode($vat_exemption_reason_code)
    {
        $this->container['vat_exemption_reason_code'] = $vat_exemption_reason_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


