<?php
/**
 * CatalogueReferenceDtoTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Dangl\AVACloud\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CatalogueReferenceDtoTest Class Doc Comment
 *
 * @category    Class
 * @description This class is used to link data between catalogues and objects.
 * @package     Dangl\AVACloud
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CatalogueReferenceDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CatalogueReferenceDto"
     */
    public function testCatalogueReferenceDto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "catalogue_reference_key"
     */
    public function testPropertyCatalogueReferenceKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "catalogue_reference_id"
     */
    public function testPropertyCatalogueReferenceId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "project_catalogues"
     */
    public function testPropertyProjectCatalogues()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "catalogue"
     */
    public function testPropertyCatalogue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
