<?php
/**
 * CatalogueReferenceDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AVACloud API 1.16.7
 *
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.16.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Dangl\AVACloud;

/**
 * CatalogueReferenceDtoTest Class Doc Comment
 *
 * @category    Class
 * @description This class is used to link data between catalogues and objects.
 * @package     Dangl\AVACloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CatalogueReferenceDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CatalogueReferenceDto"
     */
    public function testCatalogueReferenceDto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "catalogue_reference_key"
     */
    public function testPropertyCatalogueReferenceKey()
    {
    }

    /**
     * Test attribute "catalogue_reference_id"
     */
    public function testPropertyCatalogueReferenceId()
    {
    }

    /**
     * Test attribute "project_catalogues"
     */
    public function testPropertyProjectCatalogues()
    {
    }

    /**
     * Test attribute "catalogue"
     */
    public function testPropertyCatalogue()
    {
    }
}
