<?php
/**
 * GrossPriceComponentDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AVACloud API 1.29.2
 *
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.29.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Dangl\AVACloud;

/**
 * GrossPriceComponentDtoTest Class Doc Comment
 *
 * @category    Class
 * @description This is used in an ElementContainerBase to hold the price composition.
 * @package     Dangl\AVACloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GrossPriceComponentDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GrossPriceComponentDto"
     */
    public function testGrossPriceComponentDto()
    {
    }

    /**
     * Test attribute "tax_rate"
     */
    public function testPropertyTaxRate()
    {
    }

    /**
     * Test attribute "deduction_factor"
     */
    public function testPropertyDeductionFactor()
    {
    }

    /**
     * Test attribute "total_net"
     */
    public function testPropertyTotalNet()
    {
    }

    /**
     * Test attribute "total_deducted"
     */
    public function testPropertyTotalDeducted()
    {
    }

    /**
     * Test attribute "total_tax"
     */
    public function testPropertyTotalTax()
    {
    }

    /**
     * Test attribute "total_gross"
     */
    public function testPropertyTotalGross()
    {
    }

    /**
     * Test attribute "total_gross_deducted"
     */
    public function testPropertyTotalGrossDeducted()
    {
    }

    /**
     * Test attribute "total_tax_deducted"
     */
    public function testPropertyTotalTaxDeducted()
    {
    }
}
