<?php
/**
 * OenormPositionPropertiesDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AVACloud API 1.26.0
 *
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.26.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.26
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Dangl\AVACloud;

/**
 * OenormPositionPropertiesDtoTest Class Doc Comment
 *
 * @category    Class
 * @description This class models special properties that only apply to some exchange scenarios where ÖNorm is used. It is special for Positions and extends the OenormProperties base class.
 * @package     Dangl\AVACloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OenormPositionPropertiesDtoTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OenormPositionPropertiesDto"
     */
    public function testOenormPositionPropertiesDto()
    {
    }

    /**
     * Test attribute "origin_code"
     */
    public function testPropertyOriginCode()
    {
    }

    /**
     * Test attribute "opening_text_is_free_text"
     */
    public function testPropertyOpeningTextIsFreeText()
    {
    }

    /**
     * Test attribute "is_main_position"
     */
    public function testPropertyIsMainPosition()
    {
    }

    /**
     * Test attribute "is_undivided_position"
     */
    public function testPropertyIsUndividedPosition()
    {
    }
}
