<?php
/**
 * PaymentMeansTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Dangl\AVACloud\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PaymentMeansTest Class Doc Comment
 *
 * @category    Class
 * @description BG-16, BG-17 &amp; BG-18 Represents a payment means for an invoice
 * @package     Dangl\AVACloud
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PaymentMeansTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PaymentMeans"
     */
    public function testPaymentMeans()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "accountIdentifier"
     */
    public function testPropertyAccountIdentifier()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "accountName"
     */
    public function testPropertyAccountName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "serviceProviderIdentifier"
     */
    public function testPropertyServiceProviderIdentifier()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "directDebitMandateId"
     */
    public function testPropertyDirectDebitMandateId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "directDebitIban"
     */
    public function testPropertyDirectDebitIban()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "paymentId"
     */
    public function testPropertyPaymentId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "paymentCardHolderName"
     */
    public function testPropertyPaymentCardHolderName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "paymentCardPrimaryAccountNumber"
     */
    public function testPropertyPaymentCardPrimaryAccountNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "paymentCardNetworkId"
     */
    public function testPropertyPaymentCardNetworkId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
