<?php
/**
 * PositionDtoTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Dangl\AVACloud\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PositionDtoTest Class Doc Comment
 *
 * @category    Class
 * @description PositionDto
 * @package     Dangl\AVACloud
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PositionDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PositionDto"
     */
    public function testPositionDto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unitPrice"
     */
    public function testPropertyUnitPrice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unitPriceOverride"
     */
    public function testPropertyUnitPriceOverride()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quantityOverride"
     */
    public function testPropertyQuantityOverride()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "isComplementingPosition"
     */
    public function testPropertyIsComplementingPosition()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "complementsPositions"
     */
    public function testPropertyComplementsPositions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "complementingPricePercentageOverride"
     */
    public function testPropertyComplementingPricePercentageOverride()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "complementingPricePercentage"
     */
    public function testPropertyComplementingPricePercentage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unitTag"
     */
    public function testPropertyUnitTag()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "labourComponents"
     */
    public function testPropertyLabourComponents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "priceComponents"
     */
    public function testPropertyPriceComponents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quantityComponents"
     */
    public function testPropertyQuantityComponents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subDescriptions"
     */
    public function testPropertySubDescriptions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "comissionStatus"
     */
    public function testPropertyComissionStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "complementedBy"
     */
    public function testPropertyComplementedBy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "complemented"
     */
    public function testPropertyComplemented()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amountToBeEnteredByBidder"
     */
    public function testPropertyAmountToBeEnteredByBidder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "priceCompositionRequired"
     */
    public function testPropertyPriceCompositionRequired()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "useDifferentTaxRate"
     */
    public function testPropertyUseDifferentTaxRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "taxRate"
     */
    public function testPropertyTaxRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "itemNumber"
     */
    public function testPropertyItemNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "deductionFactor"
     */
    public function testPropertyDeductionFactor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "totalPrice"
     */
    public function testPropertyTotalPrice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "totalPriceGross"
     */
    public function testPropertyTotalPriceGross()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "totalPriceGrossDeducted"
     */
    public function testPropertyTotalPriceGrossDeducted()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "deductedPrice"
     */
    public function testPropertyDeductedPrice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "positionType"
     */
    public function testPropertyPositionType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "priceType"
     */
    public function testPropertyPriceType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "serviceType"
     */
    public function testPropertyServiceType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "productData"
     */
    public function testPropertyProductData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shortText"
     */
    public function testPropertyShortText()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "htmlShortText"
     */
    public function testPropertyHtmlShortText()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "longText"
     */
    public function testPropertyLongText()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "htmlLongText"
     */
    public function testPropertyHtmlLongText()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "additionType"
     */
    public function testPropertyAdditionType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "elementType"
     */
    public function testPropertyElementType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quantityAssignments"
     */
    public function testPropertyQuantityAssignments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "commerceProperties"
     */
    public function testPropertyCommerceProperties()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "alternativeTo"
     */
    public function testPropertyAlternativeTo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "alternativeIdentifier"
     */
    public function testPropertyAlternativeIdentifier()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "alternativeGroupIdentifier"
     */
    public function testPropertyAlternativeGroupIdentifier()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "isLumpSum"
     */
    public function testPropertyIsLumpSum()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "repetitionTo"
     */
    public function testPropertyRepetitionTo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "standardizedDescription"
     */
    public function testPropertyStandardizedDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "complementedByQuantities"
     */
    public function testPropertyComplementedByQuantities()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "executionDescriptionReference"
     */
    public function testPropertyExecutionDescriptionReference()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "notOffered"
     */
    public function testPropertyNotOffered()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "oenormPositionProperties"
     */
    public function testPropertyOenormPositionProperties()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "descriptionId"
     */
    public function testPropertyDescriptionId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hierarchyLevel"
     */
    public function testPropertyHierarchyLevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "addendumStatus"
     */
    public function testPropertyAddendumStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hasBidderCommentInHtmlLongText"
     */
    public function testPropertyHasBidderCommentInHtmlLongText()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gaebComplementingType"
     */
    public function testPropertyGaebComplementingType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "holdOutProperties"
     */
    public function testPropertyHoldOutProperties()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "estimatedQuantity"
     */
    public function testPropertyEstimatedQuantity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "priceCatalogueData"
     */
    public function testPropertyPriceCatalogueData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ignoreProjectCataloguePropagation"
     */
    public function testPropertyIgnoreProjectCataloguePropagation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "isMainPosition"
     */
    public function testPropertyIsMainPosition()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
