<?php
/**
 * ProjectDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AVACloud API 1.26.0
 *
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.26.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.26
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Dangl\AVACloud;

/**
 * ProjectDtoTest Class Doc Comment
 *
 * @category    Class
 * @description A Project contains all relevant information for a construction project.
 * @package     Dangl\AVACloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProjectDtoTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProjectDto"
     */
    public function testProjectDto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "price_accuracy"
     */
    public function testPropertyPriceAccuracy()
    {
    }

    /**
     * Test attribute "force_strict_totals"
     */
    public function testPropertyForceStrictTotals()
    {
    }

    /**
     * Test attribute "price_rounding_mode"
     */
    public function testPropertyPriceRoundingMode()
    {
    }

    /**
     * Test attribute "project_information"
     */
    public function testPropertyProjectInformation()
    {
    }

    /**
     * Test attribute "service_specifications"
     */
    public function testPropertyServiceSpecifications()
    {
    }

    /**
     * Test attribute "gaeb_xml_id"
     */
    public function testPropertyGaebXmlId()
    {
    }
}
