<?php
/**
 * ReferencesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AVACloud API 1.52.1
 *
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.52.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.41
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Dangl\AVACloud;

/**
 * ReferencesTest Class Doc Comment
 *
 * @category    Class
 * @description References
 * @package     Dangl\AVACloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReferencesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "References"
     */
    public function testReferences()
    {
    }

    /**
     * Test attribute "buyer_reference"
     */
    public function testPropertyBuyerReference()
    {
    }

    /**
     * Test attribute "project_reference"
     */
    public function testPropertyProjectReference()
    {
    }

    /**
     * Test attribute "contract_reference"
     */
    public function testPropertyContractReference()
    {
    }

    /**
     * Test attribute "purchase_order_reference"
     */
    public function testPropertyPurchaseOrderReference()
    {
    }

    /**
     * Test attribute "sales_order_reference"
     */
    public function testPropertySalesOrderReference()
    {
    }

    /**
     * Test attribute "receiving_advice_reference"
     */
    public function testPropertyReceivingAdviceReference()
    {
    }

    /**
     * Test attribute "dispatch_advice_reference"
     */
    public function testPropertyDispatchAdviceReference()
    {
    }

    /**
     * Test attribute "tender_or_lot_reference"
     */
    public function testPropertyTenderOrLotReference()
    {
    }

    /**
     * Test attribute "invoiced_object_identifier"
     */
    public function testPropertyInvoicedObjectIdentifier()
    {
    }
}
