<?php
/**
 * ServiceSpecificationGroupDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AVACloud API 1.9.1
 *
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.9.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Dangl\AVACloud;

/**
 * ServiceSpecificationGroupDtoTest Class Doc Comment
 *
 * @category    Class
 * @description ServiceSpecificationGroupDto
 * @package     Dangl\AVACloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServiceSpecificationGroupDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ServiceSpecificationGroupDto"
     */
    public function testServiceSpecificationGroupDto()
    {
    }

    /**
     * Test attribute "project_hourly_wage"
     */
    public function testPropertyProjectHourlyWage()
    {
    }

    /**
     * Test attribute "project_tax_rate"
     */
    public function testPropertyProjectTaxRate()
    {
    }

    /**
     * Test attribute "project_price_components"
     */
    public function testPropertyProjectPriceComponents()
    {
    }

    /**
     * Test attribute "project_item_number_schema"
     */
    public function testPropertyProjectItemNumberSchema()
    {
    }

    /**
     * Test attribute "elements"
     */
    public function testPropertyElements()
    {
    }

    /**
     * Test attribute "project_labour_time_label"
     */
    public function testPropertyProjectLabourTimeLabel()
    {
    }

    /**
     * Test attribute "contains_duplicate_item_numbers"
     */
    public function testPropertyContainsDuplicateItemNumbers()
    {
    }

    /**
     * Test attribute "ignore_duplicate_item_numbers"
     */
    public function testPropertyIgnoreDuplicateItemNumbers()
    {
    }

    /**
     * Test attribute "total_price_gross_by_tax_rate"
     */
    public function testPropertyTotalPriceGrossByTaxRate()
    {
    }

    /**
     * Test attribute "ignore_child_price_updates"
     */
    public function testPropertyIgnoreChildPriceUpdates()
    {
    }

    /**
     * Test attribute "deducted_price"
     */
    public function testPropertyDeductedPrice()
    {
    }

    /**
     * Test attribute "deduction_factor"
     */
    public function testPropertyDeductionFactor()
    {
    }

    /**
     * Test attribute "total_price"
     */
    public function testPropertyTotalPrice()
    {
    }

    /**
     * Test attribute "total_price_gross"
     */
    public function testPropertyTotalPriceGross()
    {
    }

    /**
     * Test attribute "total_price_gross_deducted"
     */
    public function testPropertyTotalPriceGrossDeducted()
    {
    }

    /**
     * Test attribute "price_type"
     */
    public function testPropertyPriceType()
    {
    }

    /**
     * Test attribute "short_text"
     */
    public function testPropertyShortText()
    {
    }

    /**
     * Test attribute "comission_status"
     */
    public function testPropertyComissionStatus()
    {
    }

    /**
     * Test attribute "item_number"
     */
    public function testPropertyItemNumber()
    {
    }

    /**
     * Test attribute "element_type"
     */
    public function testPropertyElementType()
    {
    }

    /**
     * Test attribute "is_lot"
     */
    public function testPropertyIsLot()
    {
    }

    /**
     * Test attribute "alternative_to"
     */
    public function testPropertyAlternativeTo()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }
}
