<?php
/**
 * STLBKeyDtoTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVACloud API 1.64.1
 *
 * AVACloud API specification
 *
 * The version of the OpenAPI document: 1.64.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Dangl\AVACloud\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * STLBKeyDtoTest Class Doc Comment
 *
 * @category    Class
 * @description This class represents a single key reference within the German STLB \&quot;Standardleistungsbuch Bau\&quot;
 * @package     Dangl\AVACloud
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class STLBKeyDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "STLBKeyDto"
     */
    public function testSTLBKeyDto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "artIdentifier"
     */
    public function testPropertyArtIdentifier()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "artIndex"
     */
    public function testPropertyArtIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "kindIdentifier"
     */
    public function testPropertyKindIdentifier()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
