<?php
/**
 * TokenResponseGetTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AVACloud API 1.26.0
 *
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.26.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.26
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Dangl\AVACloud\Model;

use \Dangl\AVACloud\AbstractSkippableTest;

/**
 * TokenResponseGetTest Class Doc Comment
 *
 * @category    Class
 * @description TokenResponseGet
 * @package     Dangl\AVACloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TokenResponseGetTest extends AbstractSkippableTest
{

    /**
     * Test "TokenResponseGet"
     */
    public function testTokenResponseGet()
    {
    }

    /**
     * Test attribute "access_token"
     */
    public function testPropertyAccessToken()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }

    /**
     * Test attribute "error_description"
     */
    public function testPropertyErrorDescription()
    {
    }

    /**
     * Test attribute "expires_in"
     */
    public function testPropertyExpiresIn()
    {
    }

    /**
     * Test attribute "http_error_reason"
     */
    public function testPropertyHttpErrorReason()
    {
    }

    /**
     * Test attribute "http_status_code"
     */
    public function testPropertyHttpStatusCode()
    {
    }

    /**
     * Test attribute "identity_token"
     */
    public function testPropertyIdentityToken()
    {
    }

    /**
     * Test attribute "is_error"
     */
    public function testPropertyIsError()
    {
    }

    /**
     * Test attribute "refresh_token"
     */
    public function testPropertyRefreshToken()
    {
    }

    /**
     * Test attribute "token_type"
     */
    public function testPropertyTokenType()
    {
    }

    /**
     * Test attribute "error_type"
     */
    public function testPropertyErrorType()
    {
    }
}
