<?php
/**
 * GaebConversionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AVACloud API 1.26.0
 *
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.26.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.26
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Dangl\AVACloud\Api;

use \Dangl\AVACloud\AbstractSkippableTest;

/**
 * GaebConversionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GaebConversionApiTest extends AbstractSkippableTest
{

    /**
     * Test case for gaebConversionConvertToAva
     *
     * Converts GAEB files to Dangl.AVA projects.
     *
     */
    public function testGaebConversionConvertToAva()
    {
    }

    /**
     * Test case for gaebConversionConvertToExcel
     *
     * Converts GAEB files to Excel.
     *
     */
    public function testGaebConversionConvertToExcel()
    {
    }

    /**
     * Test case for gaebConversionConvertToGaeb
     *
     * Converts GAEB files to GAEB files. Used for example when transforming or repairing GAEB files..
     *
     */
    public function testGaebConversionConvertToGaeb()
    {
    }

    /**
     * Test case for gaebConversionConvertToOenorm
     *
     * Converts GAEB files to Oenorm files.
     *
     */
    public function testGaebConversionConvertToOenorm()
    {
    }
}
