<?php
/**
 * OenormConversionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AVACloud API 1.17.0
 *
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.17.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Dangl\AVACloud;

use \Dangl\AVACloud\Configuration;
use \Dangl\AVACloud\ApiException;
use \Dangl\AVACloud\ObjectSerializer;

/**
 * OenormConversionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Dangl\AVACloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OenormConversionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for oenormConversionConvertToAva
     *
     * Converts ÖNorm files to Dangl.AVA projects.
     *
     */
    public function testOenormConversionConvertToAva()
    {
    }

    /**
     * Test case for oenormConversionConvertToExcel
     *
     * Converts ÖNorm files to Excel.
     *
     */
    public function testOenormConversionConvertToExcel()
    {
    }

    /**
     * Test case for oenormConversionConvertToGaeb
     *
     * Converts ÖNorm files to GAEB files..
     *
     */
    public function testOenormConversionConvertToGaeb()
    {
    }

    /**
     * Test case for oenormConversionConvertToOenorm
     *
     * Converts ÖNorm files to Oenorm files..
     *
     */
    public function testOenormConversionConvertToOenorm()
    {
    }
}
